--[[

***************************************************************    
*** NOTICE TO TRANSLATORS: DO NOT EDIT THIS FILE DIRECTLY! ***

We have provided a standard PO file to translation in /scripts/languages/strings.po
To add a new language:
- User a PO editor such as POEdit (http://www.poedit.net/) to translate strings.po
- Load your own PO file under /scripts/languages/language.lua

***************************************************************
]]

STRINGS=
{

    CHARACTER_NAMES =
    {
        wilson = "Íþ ¶ûÑ·¡¤P¡¤Î÷¸ñ²¨Àû",
        willow = "Þ±Âå",
        wendy = "ÎÂµÙ",
        wolfgang = "ÎÖ¶û·ò¸Ô",
        woodie = "ÎéµÏ",
        wickerbottom = "Þ±¿Ë°Í¶ÙÐ¡½ã",
        wx78 = "WX-78",
        wes = "Î¤Ë¹",
        waxwell = "ÂóË¹Íþ¶û",
        wathgrithr = "Þ±Ë¹¸çµÂ¶û",
        webber = "Î¤²®",
        unknown = "²»Ã÷ÈËÎï",
    },


    CHARACTER_QUOTES =
    {
        wilson = "\"ÎÒ Òª ÓÃ ÎÒ µÄ Òâ Äî Õ÷ ·þ Ëü £¡\"",
        willow = "\"¶« Î÷ ×Ü ÔÚ È¼ ÉÕ µÄ Ê± ºò ¸ü Ñ¤ Àö ¡£\"",
        woodie = "\"ÄÇ Ê÷ ²» ´í £¬ ÊÇ °É £¿\"",
        wendy ="\"°¢ ±È ¸Ç ¶û £¿ »Ø À´ £¡ ÎÒ »¹ Ã» ¸ú Äã Íæ ¹» ÄØ ¡£\"",
        wolfgang = "\"ÎÒ ÊÇ ´ó Á¦ Ê¿ £¡ Ã» ÓÐ ÈË µÄ Á¦ Á¿ ÄÜ ³¬ Ô½ ÎÒ £¡\"",
        wx78 = "\"Çé ¸Ð Ä£ ×é ÎÞ Ïì Ó¦\"",
        wickerbottom = "\"Ðê £¡ Í¼ Êé ¹Ý Àï ²» ×¼ Ëµ »° £¡\"",
        waxwell = "\"×Ô ÓÉ £¡\"",
        wes = "¡­¡­",
        wathgrithr = "\"Áí Ò» ¸ö Õ¹ ÏÖ ¾« Õ¿ ÑÝ ¼¼ µÄ Îè Ì¨ £¡\"",
        webber = "\"ÎÒ ÃÇ ¿É ÒÔ ¿Ë ·þ Ò» ÇÐ Äæ ¾³ £¡\"",
    },

    CHARACTER_TITLES =
    {
        wilson = "Éð Ê¿ ¿Æ Ñ§ ¼Ò",
        willow = "»ð Ö® ³è ¶ù",
        wendy = "É¥ Ç× Õß",
        woodie = "éÔ ·ò",
        wolfgang = "´ó Á¦ Ê¿",
        wx78 = "Ã» ÓÐ Áé »ê µÄ »ú Æ÷ ÈË",
        wickerbottom = "Í¼ Êé ¹Ü Àí Ô±",
        wes = "ÑÆ ¾ç ÑÝ Ô±",
        waxwell = "¿þ ÀÜ Ê¦",
        wathgrithr = "Å® Îä Éñ °ç ÑÝ Õß",
        webber = "Ã» ÓÐ ±» Ö© Öë Ïû »¯ µÄ",
    },

    CHARACTER_DESCRIPTIONS =
    {
        wilson = "* ³¤ ³ö Ò» ´ó °Ñ ºú Ðë",
        willow = "* ²» »á ±» »ð Ñæ ÉË º¦ \n * ÓÐ Ò» ¸ö ¿É °® µÄ ´ò »ð »ú \n * ½ô ÕÅ µÄ Ê± ºò »á ²» ×Ô Ö÷ µÄ ·Å »ð",
        wendy = "* ÊÜ µ½ Ëý Ë« °û Ì¥ ½ã ½ã µÄ »· ÈÆ \n * ÔÚ ºÚ °µ Àï ºÜ Êæ ·þ \n * Á¦ Æø ±È ½Ï Ð¡",
        wolfgang = "* ¶Ç ×Ó ±¥ Ê± ¸ü ¼Ó Ç¿ ´ó \n * º¦ ÅÂ ºÚ °µ ºÍ ¹Ö ÊÞ",
        wx78 = "* ²» Ìô Ê³ \n * ÉÁ µç »á ±» ³ä ÄÜ £¬ ÏÂ Óê »á ±» ÉË º¦ \n * ¿É ÒÔ ÓÃ ³Ý ÂÖ Éý ¼¶",
        wickerbottom = "* Öª µÀ ºÜ ¶à ÊÂ Çé \n * ×Ô ¼º ·¢ ÐÐ ÁË Êé ¼® \n * Ê§ Ãß Ö¢ »¼ Õß £¬ ºÜ Ìô ÌÞ Ê³ Îï",
        wes = "* ²» ÄÜ Ëµ »° \n * ºÜ ÄÑ »î ×Å \n * Ê¹ ÓÃ Æø Çò Ä§ ·¨",
        waxwell = "* ÒÂ ¹Ú ³þ ³þ µ« ºÜ ´à Èõ \n * ÄÜ ·Ö ÁÑ ×Ô ¼º µÄ ¾« Éñ \n * ´ø À´ ÁË Ëû ×Ô ¼º µÄ ½£",
        woodie = "* ÓÐ Ò» °Ñ ¿É °® µÄ ¸« ×Ó \n * ÓÐ Ò» ¸ö ¿É ÅÂ µÄ ÃØ ÃÜ",
        wathgrithr = "* ÓÐ ×Å ¹ý ÈË µÄ Õ½ ¶· ±¾ Áì \n * ´Ó µ¹ ÏÂ µÄ µÐ ÈË Éí ÉÏ µÃ µ½ Á¦ Á¿ \n * Ö» °® ³Ô Èâ",
        webber = "* ÊÇ Ò» ¸ö ¹Ö Îï \n * ¿É ÒÔ Ç× ½ü Ö© Öë \n * ³¤ ³ö Ê® ·Ö Èá »¬ µÄ ºú Ðë",
    },

    --ACTION MOUSEOVER TEXT
    ACTIONS=
    {
        TRAVEL = "ÂÃ ÐÐ",
        GNAW = "¿Ð",
        READ = "¶Á",
        MAKEBALLOON = "³ä Æø",
        SEW = "·ì ÈÒ",
        GIVE = 
        {
            GENERIC  = "¸ø Óè",
            NOTREADY = "°² ÖÃ",
            READY    = "¼À Æ·",
        },
        DROP = 
        {
            GENERIC = "¶ª µô",
            SETTRAP = "°² ÖÃ ÏÝ Úå",
            SETMINE = "°² ÖÃ µØ À×",
            PLACELANTERN = "°² ÖÃ",
        },
        BUILD = "½¨ Ôì",
        PICK = "²É ¼¯",
        REPAIR = "ÐÞ Àí",
        PICKUP = "¼ñ Æð",
        CHOP = "¿³ µ¹",
        FERTILIZE = "¹à ¸È",
        SMOTHER = "Ïû Ãð",
        MANUALEXTINGUISH = "Ïû Ãð",
        RANGEDSMOTHER = "Ïû Ãð",
        RANGEDLIGHT = "µã È¼",
        EAT = "³Ô µô", 
        BAIT = "·Å ÉÏ ÓÕ ¶ü",
        COOK = "Åë µ÷",
        ADDFUEL = "Ìí ¼Ó È¼ ÁÏ",
        ADDWETFUEL = "Ìí ¼Ó Êª È¼ ÁÏ",
        LIGHT = "µã È¼",
        EXTINGUISH = "Ïû Ãð",
        LOOKAT = "¼ì ²é",
        TALKTO = "½» Ì¸ £¬ ºÍ",
        MINE = "¿ª ²É",
        ATTACK = 
        {
            GENERIC = "¹¥ »÷",
            SMASHABLE = "ÑÐ Ëé",
        },
        WALKTO = "×ß µ½",
        CHECKTRAP = "¼ì ²é",
        BUILD = "½¨ Ôì",
        CRAFT = "ÖÆ ×÷",
        PLANT = "ÖÖ Ö²",
        HARVEST = "ÊÕ »ñ",
        GOHOME = "»Ø ¼Ò",
        DIG = "ÍÚ ¾ò",
        SLEEPIN = "Ë¯ ¾õ",
        EQUIP = "×° ±¸",
        TERRAFORM = "ÍÚ ¾ò",
        UNEQUIP = "Ð¶ ÏÂ",
        RESEARCH = "ÑÐ ¾¿",
        SHAVE = "¹Î",
        DRY = "¸É Ôï",
        STORE = 
        {
            GENERIC = "´¢ ´æ",
            COOK = "Åë µ÷",
            IMPRISON = "·Å µ½ Àï ±ß",
        },
        RUMMAGE =
        {
            GENERIC = "´ò ¿ª",
            CLOSE = "¹Ø ±Õ",
        },
        DEPLOY = 
        {
            GENERIC = "ÖÖ Ö²",
            GROUNDTILE = "·Å ÖÃ µØ µã",
            WALL = "½¨ Ôì Ç½ ±Ú",
            TURRET = "°² ÖÃ",
        },
        
        PLAY = "ÑÝ ×à",
        NET = "²¶ ×½",
        CATCH = "²¶ ×½",
        FISH = "´¹ µö",
        REEL =
        {
            GENERIC = "Ìá ¸Í",
            REEL = "Ñï ¸Í",
            CANCEL = "Í£ Ö¹ ´¹ µö",
        },
        POLLINATE = "Ê© ·Ê",
        HAMMER = "´¸ ×Ó",
        RESETMINE = "ÖØ Éè",
        ACTIVATE = {
            GENERIC = "¼¤ »î",
            INVESTIGATE = "µ÷ ²é",
            SPELUNK = "¶´ Ñ¨ ÑÐ ¾¿",
            CLIMB = "ÅÊ ÅÀ",
            ACCOMPLISH = "²ø ÈÆ",
        },
        JUMPIN = "Ìø Èë",
        MURDER = "É± º¦",
        HEAL = "ÖÎ ÁÆ",
        UNLOCK = 
        {
            GENERIC = "½â Ëø",
            LOCK = "Ëø ¶¨",
        },
        TEACH = "Ñ§ Ï°",
        TURNON = "´ò ¿ª",
        TURNOFF = "¹Ø ±Õ",
        USEITEM = "Ê¹ ÓÃ",
        TAKEITEM = "ÄÃ ×ß Îï Æ·",
        CASTSPELL = "Ê© ·Å ·û Öä", --"Cast Spell on"
        BLINK = "´« ËÍ",
        COMBINESTACK = "·Å µ½ Ò» Æð",
        WHACK = "ÖØ »÷",
        BURY = "Âñ",
        FEED = "Î¹ Ñø",
        FAN = "ÉÈ",
        UPGRADE = "Éý ¼¶",
    },

    LMB              = "\255", --"ÿ",
    RMB              = "\254", --"?,
    A_BTN            = "\253", --"?,
    B_BTN            = "\252", --"?,
    X_BTN            = "\251", --"?,
    Y_BTN            = "\250", --"?, 
    START_BTN        = "\249", --"?,
    BACK_BTN         = "\248", --"?,
    LEFT_THUMB       = "\247", --"?,
    L1_BTN           = "\246", --"?,
    L2_BTN           = "\245", --"?,
    RIGHT_THUMB      = "\244", --"?,
    R1_BTN           = "\243", --"?,
    R2_BTN           = "\242", --"?,
    DPAD_DOWN        = "\241", --"?, 
    DPAD_LEFT        = "\240", --"?,
    DPAD_UP          = "\239", --"?,
    DPAD_RIGHT       = "\238", --"?,
    


    SELECT = "Ñ¡ Ôñ",
    DROPALL = "È« ²¿ ·Å ÏÂ",

    INSPECTMOD = "¼ì ²é",
    STACKMOD = "ÄÃ ×ß Ò» °ë",
    TRADEMOD = "ÒÆ ¶¯",
    SWAP = "½» »»",

    WITHEREDITEM = "¿Ý Î®",
    SMOLDERINGITEM = "Ñ¬ ÉÕ",

    WET_PREFIX =
    {
        NONE = "",
        GENERIC = "Êª",
        RABBITHOLE = "µ¹ Ëú",
        CLOTHING = "½þ ÅÝ",
        FUEL = "»ý Ë®",
        TOOL = "»¬",
        FOOD = "³± Êª",
        GOOP = "ºÜ",
    },

    NAMES =
    {


        DEFAULT = "¿â ´æ Îï Æ·",

        LUCY = "Â¶ Î÷ ¸«",
        BOOK_BIRDS = "ÊÀ ½ç ÉÏ µÄ Äñ",
        BOOK_TENTACLES = "ÔÚ ´¥ ÊÖ ÉÏ",
        BOOK_GARDENING = "Ó¦ ÓÃ Ô° ÒÕ Ñ§",
        BOOK_SLEEP = "Ë¯ Ç° ¹Ê ÊÂ",
        BOOK_BRIMSTONE = "Ä© ÈÕ ½« ÖÁ £¡",

        ANCIENT_ALTAR ="Ô¶ ¹Å Î± ¿Æ Ñ§ »ù µØ",
        ANCIENT_ALTAR_BROKEN ="ÆÆ Ëé µÄ Ô¶ ¹Å Î± ¿Æ Ñ§ »ù µØ",
        ANCIENT_STATUE ="Ô¶ ¹Å µñ Ïñ",
        CHESSJUNK1 = "ÆÆ Ëé µÄ »ú Ðµ",
        CHESSJUNK2 = "ÆÆ Ëé µÄ »ú Ðµ",
        CHESSJUNK3 = "ÆÆ Ëé µÄ »ú Ðµ",
        ABIGAIL_FLOWER = "°¢ ±È ¸Ç ¶û Ö® »¨",
        BALLOONS_EMPTY = "Ò» ¶Ñ Æø Çò",
        BALLOON = "Æø Çò",    
        LIGHTER = "Þ± Âå µÄ ´ò »ð »ú",
        COMPASS = "Ö¸ ÄÏ Õë",
        MUSHTREE_TALL = "Ä¢ ¹½ Ê÷",
        MUSHTREE_MEDIUM = "ºì Ä¢ ¹½",
        MUSHTREE_SMALL = "ÂÌ É« ¹à Ä¾ ´Ô",
        SPIDER_HIDER="¶´ Ñ¨ Ö© Öë",
        SPIDER_SPITTER="Åç ÍÂ ³æ",
        SEWING_KIT = "·ì ÈÒ ¹¤ ¾ß °ü",
        RED_MUSHROOM = "ºì É« ¹à Ä¾ ´Ô",
        RED_CAP = "ºì ¹½ Í·",
        RED_CAP_COOKED = "Öó Êì µÄ ºì Ä¢ ¹½",
        GREEN_MUSHROOM = "ÂÌ Ä¢ ¹½",
        GREEN_CAP = "ÂÌ ¹½ Í·",
        GREEN_CAP_COOKED = "Öó Êì µÄ ÂÌ Ä¢ ¹½",
        BLUE_MUSHROOM = "À¶ Ä¢ ¹½",
        BLUE_CAP_COOKED = "Öó Êì µÄ À¶ Ä¢ ¹½",
        BLUE_CAP = "À¶ ¹½ Í·",

        CARROT = "ºú ÂÜ ²·",
        PUMPKIN = "ÄÏ ¹Ï",
        DRAGONFRUIT = "»ð Áú ¹û",
        POMEGRANATE = "Ê¯ Áñ",
        CORN = "Óñ Ã×",
        DURIAN = "Áñ Á«",
        EGGPLANT = "ÇÑ ×Ó",
        ICEBOX = "±ù Ïä",
        CARROT_SEEDS = "ºú ÂÜ ²· ÖÖ ×Ó",
        PUMPKIN_SEEDS = "ÄÏ ¹Ï ÖÖ ×Ó",
        DRAGONFRUIT_SEEDS = "»ð Áú ¹û ÖÖ ×Ó",
        POMEGRANATE_SEEDS = "Ê¯ Áñ",
        CORN_SEEDS = "Óñ Ã× ÖÖ ×Ó",
        DURIAN_SEEDS = "Áñ Á« ÖÖ ×Ó",
        EGGPLANT_SEEDS = "ÇÑ ×Ó ÖÖ ×Ó",
        WATERMELON_SEEDS = "Î÷ ¹Ï ÖÖ ×Ó",
        MANRABBIT_TAIL = "ÍÃ Ã«",
        BUNNYMAN = "´ó ÍÃ ¶ù",
        PIGGUARD = "Öí Íõ ÊÌ ÎÀ",
        NITRE = "Ïõ Ê¯",
        GUNPOWDER = "»ð Ò©",
        BIRD_EGG = "¼¦ µ°",
        BIRD_EGG_COOKED = "Êì ¼¦ µ°",
        ROTTENEGG = "¸¯ ÀÃ µÄ ¼¦ µ°",
        
        WINTEROMETER = "ÎÂ ¶È Ö¸ Ê¾ ¼Æ",
        RAINOMETER = "Êª ¶È ¼Æ",
        SPOILED_FOOD = "¸¯ ÀÃ µÄ Ê³ Îï",
        BERRIES = "½¬ ¹û",
        BACKPACK = "±³ °ü",
        PIGGYBACK = "Öí Æ¤ ±³ °ü",
        REDGEM ="ºì ±¦ Ê¯",
        PURPLEGEM = "×Ï ±¦ Ê¯",
        GREENGEM = "ÂÌ ±¦ Ê¯",
        ORANGEGEM = "³È ±¦ Ê¯",
        YELLOWGEM = "»Æ ±¦ Ê¯",
        HOUNDSTOOTH = "Àû ³Ý",
        SWEATERVEST = "¾« ÖÂ ±³ ÐÄ",
        CARROT_COOKED = "¿¾ ºú ÂÜ ²·",
        PUMPKIN_COOKED = "ÈÈ ÄÏ ¹Ï",
        DRAGONFRUIT_COOKED = "¾« ÖÂ »ð Áú ¹û",
        POMEGRANATE_COOKED = "Ê¯ Áñ Æ¬",
        CORN_COOKED = "±¬ Ã× »¨",
        DURIAN_COOKED = "³¬ ³ô Áñ Á«",
        EGGPLANT_COOKED = "ºì ÉÕ ÇÑ ×Ó",
        BERRIES_COOKED = "ÈÈ ìÐ ½¬ ¹û",
        CAVE_ENTRANCE_CLOSED = "±» ¶Â ×¡ µÄ ¶´ Ñ¨",
        CAVE_ENTRANCE_OPEN = "Âä Ë® ¶´",
        CAVE_ENTRANCE_OPEN_CAVE = "¸ü Éî",  
        CAVE_ENTRANCE_CLOSED_CAVE = "±» ¶Â ×¡ µÄ ¶´",
        RABBITHOUSE = "ÍÃ ×Ó ÎÑ",
        CAVE_EXIT = "Éþ Ë÷",
        UMBRELLA = "Óê É¡",
        KRAMPUS_SACK = "¿² ²· Ë¹ ±³ °ü",

        TURF_ROAD = "ÂÑ Ê¯ Â·",
        TURF_ROCKY = "ÑÒ Ê¯ ²Ý Æ¤",
        TURF_DIRT = "ÎÛ ¹¸ ²Ý Æ¤",
        TURF_SAVANNA = "ÈÈ ´ø ²Ý Ô­ ²Ý Æ¤",
        TURF_GRASS = "³¤ ²Ý ²Ý Æ¤",
        TURF_FOREST = "É­ ÁÖ²Ý Æ¤",
        TURF_MARSH = "ÕÓ Ôó ²Ý Æ¤",
        TURF_WOODFLOOR = "Ä¾ ÖÊ µØ °å",
        TURF_CARPETFLOOR = "µØ Ìº µØ °å",
        TURF_CHECKERFLOOR = "·½ ¸ñ µØ °å",

        TURF_CAVE = "Äñ ·à ²Ý µØ",
        TURF_FUNGUS = "¾ú Àà ²Ý µØ",
        TURF_SINKHOLE = "Õ³ »¬ ²Ý µØ",
        TURF_UNDERROCK = "¶´ Ñ¨ Ê¯ µØ",
        TURF_MUD = "Äà Å¢ ²Ý µØ",
        TURF_DESERTDIRT = "É³ ÖÊ ²Ý µØ",
        TURF_DECIDUOUS = "Âä Ò¶ ²Ý µØ",

        TURF_WEBBING = "Öë Íø µØ ÐÎ",
        
        COOKPOT = "Åë µ÷ ¹ø",
        DUG_GRASS = "³¤ ²Ý ´Ø",
        DUG_SAPLING = "Ê÷ Ãç",
        DUG_BERRYBUSH = "½¬ ¹û ¹à Ä¾ ´Ô",
        DUG_BERRYBUSH2 = "½¬ ¹û ¹à Ä¾ ´Ô",
        DUG_MARSH_BUSH = "¼â ´Ì ¹à Ä¾",
        
        FOOTBALLHAT="Öí Æ¤ éÏ é­ Çò Í· ¿ø",
        PIGSKIN = "Öí Æ¤",
        AXE = "¸« Í·",
        HAMMER = "´¸ ×Ó",
        GOLDENAXE = "»Æ ½ð ¸« Í·",
        MEAT = "´ó Èâ ¿é",
        COOKEDMEAT = "Èâ ÅÅ",
        MEAT_DRIED = "´ó ¿é Èâ ¸É",
        SMALLMEAT = "Ð¡ Èâ ¿é",
        COOKEDSMALLMEAT = "Êì Èâ ¿é",
        SMALLMEAT_DRIED = "Ð¡ ¿é Èâ ¸É",
        MONSTERMEAT = "¹Ö ÊÞ Èâ",
        COOKEDMONSTERMEAT = "Êì ¹Ö ÊÞ Èâ",
        MONSTERMEAT_DRIED = "¹Ö ÊÞ Èâ ¸É",
        PLANTMEAT = "¶à Ò¶ µÄ Èâ",
        PLANTMEAT_COOKED = "Öó Êì µÄ ¶à Ò¶ Èâ",
        TRAP = "ÏÝ Úå",
        LOG = "Ä¾ ²Ä",
        HAMBAT = "»ð ÍÈ Çò °ô",
        LIVINGLOG = "Éú Ãü Ö® Ä¾",
        TWIGS = "Ð¡ Ê÷ Ö¦",
        CUTGRASS = "¸î ÏÂ µÄ ²Ý",
        PETALS = "»¨ °ê",
        PETALS_EVIL = "¶ñ Ä§ »¨ °ê",
        ADVENTURE_PORTAL = "Âó Ë¹ Íþ ¶û µÄ ÃÅ",
        POOP = "±ã ±ã",
        TORCH = "»ð °Ñ",
        SEEDS = "ÖÖ ×Ó",
        HOUND = "ÁÔ È®",
        FIREHOUND = "ºì É« ÁÔ È®",
        SEEDS_COOKED = "¿¾ ÖÖ ×Ó",
        SILK = "Ë¿ Ïß",
        SPIDERGLAND = "Ö© Öë ÏÙ Ìå",
        TRAP_TEETH = "Àû ³Ý ÏÝ Úå",
        TRAP_TEETH_MAXWELL = "Âó Ë¹ Íþ ¶û µÄ Àû ³Ý ÏÝ Úå",
        KRAMPUS = "¿² ²· Ë¹",
        ROCK_LIGHT = "»ð É½ ¿Ó",
        ROCKS = "ÑÒ Ê¯",
        ICE = "±ù",
        FLINT = "ìÝ Ê¯",
        AMULET = "ÖØ Éú ¡¤ »¤ ·û",
        BLUEAMULET = "º® ±ù ¡¤ »¤ ·û",
        PURPLEAMULET = "ÃÎ ÷Ê ¡¤ »¤ ·û",
        YELLOWAMULET = "Ä§ Á¦ Ö® ¹â",
        ORANGEAMULET = "Ê° È¡ ¡¤ »¤ ·û",
        GREENAMULET = "½¨ ²Ä ¡¤ »¤ ·û",
        PICKAXE = "º× ×ì ³ú",
        GOLDENPICKAXE = "»Æ ½ð º× ×ì ³ú",
        SHOVEL = "Ìú ²ù",
        GOLDENSHOVEL = "»Æ ½ð Ìú ²ù",
        PITCHFORK = "²Ý ²æ",
        GOLDENPITCHFORK = "»Æ ½ð ²Ý ²æ",
        BEEFALO = "Æ¤ ¸¥ Â¦ Å£",
        BABYBEEFALO = "Ð¡ Æ¤ ¸¥ Â¦ Å£",
        BERRYBUSH = "½¬ ¹û ¹à Ä¾ ´Ô",
        BERRYBUSH2 = "½¬ ¹û ¹à Ä¾ ´Ô",
        SUNKBOAT = "´¬",
        BONFIRE = "óô »ð ¶Ñ",
        CAMPFIRE = "óô »ð",
        CROW = "ÎÚ Ñ»",
        ROBIN = "ºì È¸",
        ROBIN_WINTER = "Ñ© È¸",
        EVERGREEN = "³£ Çà Ê÷",
        EVERGREEN_SPARSE = "´Ö ×³ µÄ ³£ Çà Ê÷",
        SLOW_FARMPLOT = "»ù ±¾ Å© ³¡",
        FAST_FARMPLOT = "¸ß ¼¶ Å© ³¡",
        FIRE = "»ð",
        COLDFIRE = "±ù Ñæ óô »ð",
        COLDFIREPIT = "±ù Ñæ Ê¯ Í· Óª »ð",
        FIREPIT = "Ê¯ Í· Óª »ð",
        HEATROCK = "±£ Å¯ Ê¯",
        FLOWER = "»¨",
        FLOWER_EVIL = "¶ñ Ä§ Ö® »¨",
        FIREFLIES = "Ó© »ð ³æ",
        GHOST = "¹í »ê",
        GRASS = "²Ý",
        DEPLETED_GRASS = "²Ý",
        GRAVESTONE = "Ä¹ ±®",
        HOMESIGN = "Â· ±ê ÅÆ",
        MAXWELL = "Âó Ë¹ Íþ ¶û",
        MOUND = "·Ø Ä¹",
        PIGHOUSE = "Öí Éá",
        PIGMAN = "Öí Í· ÈË",
        CROP = "Å© ×÷ Îï",
        POND = "³Ø ÌÁ",
        POND_MOS = "³Ø ÌÁ",
        POND_CAVE = "³Ø ÌÁ",
        RABBIT = "ÍÃ ×Ó",
        RABBITHOLE = "ÍÃ ×Ó ÎÑ",
        ROCK1 = "ÂÑ Ê¯",
        ROCK2 = "ÂÑ Ê¯",
        ROCK_FLINTLESS = "ÂÑ Ê¯",
        ROCK_ICE = "±ù ¾§",
        ROCK_ICE_MELTED = "ÈÚ »¯ µÄ ±ù ¾§",
        INSANITYROCK = "·½ ¼â ±®",
        SANITYROCK = "·½ ¼â ±®",
        SKELETON = "¹Ç ¼Ü",
        PIGHEAD = "Öí ÈË Í·",
        MERMHEAD = "Óã ÈË Í·",

        SAPLING = "Ê÷ Ãç",
        SPIDER = "Ö© Öë",
        SPIDERDEN = "Ö© Öë ³²",
        SPIDER_WARRIOR = "Ö© Öë Õ½ Ê¿",
        TENT = "ÕÊ Åñ",
        SIESTAHUT = "Îç Ë¯ Åï",
        PIGTORCH = "Öí ÈË »ð ¾æ",
        
        WILSON = "Íþ ¶û Ñ·",
        WILLOW = "Þ± Âå",
        WENDY = "ÎÂ µÙ",
        WOLFGANG = "ÎÖ ¶û ·ò ¸Ô",
        WOODIE = "Îé µÏ",
        WICKERBOTTOM = "Þ± ¿Ë °Í ¶Ù",
        WX78 = "Wx78",
        WES = "Î¤ Ë¹",
        
        PIGKING = "Öí ÈË ¹ú Íõ",
        STRAWHAT = "²Ý Ã±",
        TOPHAT = "¸ß Àñ Ã±",
        FLOWERHAT = "»¨ »·",
        BEEFALOHAT = "êó Å£ Ã« ÑÏ ¶¬ Ã±",
        FEATHERHAT = "Óð Ã« Ã±",
        ARMORWOOD = "Ä¾ ÖÆ ¿ø ¼×",
        ARMORGRASS = "²Ý µØ ¿ø ¼×",
        ARMORMARBLE = "´ó Àí Ê¯ ¿ø ¼×",
        ARMOR_SANITY = "°µ Ò¹ ¿ø ¼×",
        SPEAR = "³¤ Ã¬",
        TENTACLESPIKE = "´¥ ÊÖ ¼â ´Ì",
        TENTACLE = "´¥ ÊÖ",
        TENTACLE_PILLAR = "´ó ´¥ ÊÖ",
        TENTACLE_PILLAR_ARM = "Ð¡ ´¥ ÊÖ",
        TENTACLE_GARDEN = "´ó ´¥ ÊÖ",
        ROPE = "Éþ Ë÷",
        RESURRECTIONSTATUE = "Èâ ¿é µñ Ïñ",
        RESURRECTIONSTONE = "ÊÔ ½ð Ê¯",
        BOARDS = "Ä¾ °å",
        CUTSTONE = "Ê¯ ×© ¿é",
        GOLDNUGGET = "½ð ¿é",
        RESEARCHLAB = "¿Æ Ñ§ »ú Æ÷",
        RESEARCHLAB2 = "Á¶ ½ð Òý Çæ",
        RESEARCHLAB3 = "°µ Ó° ²Ù ×Ý Æ÷",
        RESEARCHLAB4 = "Ä§ ·¨ Ã± ×Ó",
        PLANT_NORMAL = "Å© ×÷ Îï",
        RAZOR = "Ìê µ¶",
        BEARDHAIR = "ºú Ðë",
        TREASURECHEST = "Ïä ×Ó",
        SKULLCHEST = "÷¼ ÷Ã Ïä",
        PANDORASCHEST = "×° ÊÎ Ïä",
        MINOTAURCHEST = "´ó ºÀ »ª Ïä ×Ó",
        CHESTER = "ÇÐ Ë¹ ÌØ ¹·",
        CHESTER_EYEBONE = "ÇÐ Ë¹ ÌØ ÑÛ ¹Ç",
        BEDROLL_STRAW = "µ¾ ²Ý ¾í",
        BEDROLL_FURRY = "Ã« Æ¤ ÆÌ ¸Ç",
        BEEFALOWOOL = "êó Å£ Ã«",
        PINECONE = "ËÉ ¹û",
        PINECONE_SAPLING = "³£ Çà Ê÷ Ê÷ Ãç",
        SPIDEREGGSACK = "Ö© Öë ÂÑ",
        CHARCOAL = "Ä¾ Ì¿",
        ASH = "»Ò ½ý",
        ASH_REMAINS = "ÒÅ º¡",
        MANDRAKE = "Âü µÂ À­ ²Ý",
        COOKEDMANDRAKE = "ÊìÂüµÂÀ­²Ý",
        REEDS = "Â« Î­",
        CUTREEDS = "¸î ºÃ µÄ Â« Î­",
        MARSH_PLANT = "ÖÖ Ö²",
        TUMBLEWEED = "·ç ¹ö ²Ý",
        MARSH_BUSH = "¼â ´Ì ¹à Ä¾",
        PAPYRUS = "Ö½ É¯ ²Ý",
        MARSH_TREE = "Õë Ò¶ Ê÷",
        PANFLUTE = "ÅÅ óï",
        BUGNET = "²¶ ³æ Íø",
        FROG = "Çà ÍÜ",
        FISHINGROD = "µö ¸Í",
        FISH = "Óã",
        FISH_COOKED = "Êì Óã",
        HONEY = "·ä ÃÛ",
        HONEYCOMB = "·ä ³²",
        BEEHIVE = "·ä ÎÑ",
        BEEBOX = "ÃÛ ·ä Ïä",
        BEE = "ÃÛ ·ä",
        DEVTOOL = "¿ª ·¢ ¹¤ ¾ß",
        KILLERBEE = "É± ÈË ·ä",
        WASPHIVE = "É± ÈË ·ä ³²",
        MOSQUITO = "ÎÃ ×Ó",
        BEEHAT = "Ñø ·ä ÈË µÄ Ã± ×Ó",
        STINGER = "·ä ´Ì",
        BUTTERFLY = "ºû µû",
        BUTTERFLYWINGS = "ºû µû ³á °ò",
        BUTTER = "»Æ ÓÍ",
        FROGLEGS = "Çà ÍÜ ÍÈ",
        FROGLEGS_COOKED = "Êì Çà ÍÜ ÍÈ",
        TALLBIRD = "¸ß ½Å Äñ",
        SMALLBIRD = "Ð¡ Äñ",
        TEENBIRD = "Ð¡ ¸ß ½Å Äñ",
        WALRUS = "º£ Ïó",
        WALRUS_CAMP = "º£ Ïó ³² Ñ¨",
        WALRUS_TUSK = "º£ Ïó ³¤ ÑÀ",
        WALRUSHAT = "ËÕ ¸ñ À¼ º® ¶¬ Ã±",
        LITTLE_WALRUS ="Ð¡ º£ Ïó",
        PUMPKIN_LANTERN = "ÄÏ ¹Ï Ó« ¹â µÆ",
        TALLBIRDNEST = "¸ß ½Å Äñ ³² Ñ¨",
        TALLBIRDEGG = "¸ß ½Å Äñ µ°",
        TALLBIRDEGG_CRACKED = "·õ »¯ ÖÐ µÄ ¸ß ½Å Äñ µ°",
        TALLBIRDEGG_COOKED = "ÓÍ ¼å ¸ß ½Å Äñ µ°",
        FEATHER_CROW = "ºÚ É« Óð Ã«",
        FEATHER_ROBIN = "ºì É« Óð Ã«",
        FEATHER_ROBIN_WINTER = "À¶ É« Óð Ã«",
        BIRDTRAP = "²¶ Äñ Æ÷",
        BLOWDART_SLEEP = "Âé ×í ´µ Õë",
        BLOWDART_FIRE = "»ð Ñæ ´µ Õë",
        BLOWDART_PIPE = "Àû ³Ý ´µ ¼ý",
        BEEMINE = "ÃÛ ·ä µØ À×",
        BEEMINE_MAXWELL = "Âó Ë¹ Íþ ¶û µÄ ÃÛ ·ä Õ¨ µ¯",
        BIRDCAGE = "Äñ Áý",
        SPIDERQUEEN = "Ö© Öë Å® Íõ",
        EARMUFFSHAT = "ÍÃ Ã« ¶ú Ì×",
        WINTERHAT = "º® ¶¬ Ã±",
        HORN = "Ò° Å£ ½Ç",
        ONEMANBAND = "¶À ×à ÀÖ Æ÷",
        STATUEHARP = "Ö± Á¢ µñ Ïñ",
        STATUEMAXWELL = "Âó Ë¹ Íþ ¶û µñ Ïñ",
        MAXWELLLIGHT = "Âó Ë¹ Íþ ¶û Ö® ¹â",
        MAXWELLKEY = "°µ Ó° Ô¿ ³×",
        
        TELEPORTATO_RING = "»· ×´ ´« ËÍ »ú Áã ¼þ",
        TELEPORTATO_BOX = "ºÐ ×´ ´« ËÍ »ú Áã ¼þ",
        TELEPORTATO_CRANK = "Çú ±ú ×´ ´« ËÍ »ú Áã ¼þ",
        TELEPORTATO_POTATO = "Çò ×´ ´« ËÍ »ú Áã ¼þ",
        TELEPORTATO_BASE = "´« ËÍ »ú Áã ¼þ µ× ×ù",
        TELEPORTATO_CHECKMATE = "´« ËÍ »ú Áã ¼þ µ× ×ù",

        
        TRINKET_1 = "ÈÚ »¯ µÄ ´ó Àí Ê¯",
        TRINKET_2 = "¼Ù ¿¨ ×æ µÑ",
        TRINKET_3 = "¸è µÂ ½á",
        TRINKET_4 = "µØ ¾« Íæ Å¼",
        TRINKET_5 = "Ð¡ ÐÍ »ð ¼ý ·É ´¬",
        TRINKET_6 = "ÆÆ ÀÃ µç Ïß",
        TRINKET_7 = "Çò Óë ½± ±­",
        TRINKET_8 = "Ó² »¯ Ïð ½º Èû",
        TRINKET_9 = "²» Æ¥ Åä µÄ Å¥ ¿Û",
        TRINKET_10 = "¶þ ÊÖ ¼Ù ÑÀ",
        TRINKET_11 = "°ë ÌÉ »ú Æ÷ ÈË",
        TRINKET_12 = "¸É ±ñ µÄ ´¥ ÊÖ",

        CARROT_PLANTED = "ºú ÂÜ ²·",
        LEIF = "Ê÷ ¾« ÊØ ÎÀ",
        LEIF_SPARSE = "Ê÷ ¾« ÊØ ÎÀ",

        BUTTERFLYMUFFIN = "»Æ ÓÍ ËÉ ±ý",
        FROGGLEBUNWICH = "ÍÜ ÍÈ Èý Ã÷ ÖÎ",
        HONEYHAM = "ÃÛ Ö­ »ð ÍÈ",
        DRAGONPIE = "»ð Áú ¹û ÅÉ",
        TAFFY = "Ì« åú ÌÇ",
        PUMPKINCOOKIE = "ÄÏ ¹Ï ±ý",
        KABOBS = "¿¾ Èâ ´®",
        MANDRAKESOUP = "Âü µÂ À­ ²Ý ÌÀ",
        BACONEGGS = "Åà ¸ù ¼å µ°",
        BONESTEW = "Èâ ÌÀ",
        PEROGIES = "²¨ À¼ µ° ½È",
        WETGOOP = "Ò» ÍÓ ºý ºý",
        RATATOUILLE = "Êß ²Ë Ê² ½õ",
        FRUITMEDLEY = "Ë® ¹û Ê¥ ´ú",
        FISHTACOS ="Õ¨ Óã ÅÅ",
        WAFFLES ="»ª ·ò ±ý",
        TURKEYDINNER = "»ð ¼¦ ´ó ²Í",
        DRUMSTICK = "¼¦ ÍÈ",
        DRUMSTICK_COOKED = "ÓÍ ¼å ¸ß ½Å Äñ µ°",
        TENTACLESPOTS = "°ß µã ´¥ ÊÖ Æ¤",
        PERD = "ÐÛ »ð ¼¦",
        ABIGAIL = "°¢ ±È ¸Ç ¶û",
        MINERHAT = "¿ó ¹¤ Ã±",
        FISHSTICKS = "Õ¨ Óã ÅÅ",
        STUFFEDEGGPLANT = "Ïã ËÖ ÇÑ ºÐ",
        HONEYNUGGETS = "ÃÛ Ö­ »ð ÍÈ",
        MEATBALLS = "Èâ Íè",
        JAMMYPRESERVES = "¹û ½´ ÃÛ ½¤",
        MONSTERLASAGNA = "¹Ö Îï Ç§ ²ã ±ý",
        SPIDERHAT = "Ö© Öë Ã±",
        WORMHOLE = "³æ ¶´",
        WORMHOLE_LIMITED_1 = "ÏÞ ¶¨ °æ ³æ ¶´",
        
        WALL_WOOD_ITEM = "Ä¾ Ç½",
        WALL_STONE_ITEM = "Ê¯ Ç½",
        WALL_RUINS_ITEM = "îû ¿ó Ç½ ±Ú",
        WALL_HAY_ITEM = "¸É ²Ý Ç½",

        WALL_WOOD = "Ä¾ Ç½",
        WALL_STONE = "Ê¯ Ç½",
        WALL_RUINS = "îû ¿ó Ç½ ±Ú",
        WALL_HAY = "¸É ²Ý Ç½",
        ANIMAL_TRACK = "¶¯ Îï ×ã ¼£",
        DIRTPILE = "¿É ÒÉ µÄ ÍÁ ¶Ñ",
        KOALEFANT_SUMMER = "´ó Ïó",
        KOALEFANT_WINTER = "¶¬ Ïó",
        TRUNK_SUMMER = "ºì É« Ïó ±Ç",
        TRUNK_WINTER = "À¶ É« Ïó ±Ç",
        TRUNK_COOKED = "¿¾ Êì Ïó ±Ç",
        TRUNKVEST_SUMMER = "ÏÄ ÈÕ ±³ ÐÄ",
        TRUNKVEST_WINTER = "º® ¶¬ ±³ ÐÄ",
        BOOMERANG = "»Ø Ðý ïÚ",
        BUSHHAT = "´Ô ÁÖ Ã±",
        
        CRAWLINGHORROR = "ÅÀ ÐÐ ¿Ö ¾å »¯ Éí",
        TERRORBEAK = "¼â à¹ ¿Ö ¾å »¯ Éí",
        CRAWLINGNIGHTMARE = "ÅÀ ÐÐ µÄ ÃÎ ÷Ê",
        NIGHTMAREBEAK = "ÃÎ ÷Ê à¹",
        NIGHTMAREFUEL = "Ø¬ ÃÎ È¼ ÁÏ",
        NIGHTLIGHT = "°µ Ò¹ ÕÕ Ã÷ µÆ",
        NIGHTSWORD = "°µ Ò¹ µ¶",
        
        DEERCLOPS = "¶À ÑÛ ¾Þ Â¹",
        BLUEGEM = "À¶ ±¦ Ê¯",

        ICESTAFF = "±ù Ä§ ÕÈ",
        FIRESTAFF = "»ð Ä§ ÕÈ",
        TELESTAFF = "´« ËÍ ¡¤ ·¨ ÕÈ",
        TELEBASE = "´« ËÍ ¡¤ ½Ú µã",
        GEMSOCKET = "±¦ Ê¯ ¿´ Ì¨",
        ORANGESTAFF = "ÒÆ ¶¯ ·¨ ÕÈ",
        GREENSTAFF = "»Ù Ãð È¨ ÕÈ",
        YELLOWSTAFF = "»½ ÐÇ Õß ·¨ ÕÈ",

        ICEHOUND = "À¶ É« ÁÔ È®",
        PENGUIN = "Æó Å¸",
        DEERCLOPS_EYEBALL = "¾Þ Â¹ ÑÛ Çò",
        GEARS = "³Ý ÂÖ",
        NITRE = "Ïõ Ê¯",
        MAXWELLHEAD = "Âó Ë¹ Íþ ¶û Ö® Ê×",
        DEADLYFEAST = "ÖÂ Ãü Ê¢ Ñç",
               
        SINKHOLE = "Ðþ Îä ÑÒ",
        BASALT = "Ðþ Îä ÑÒ",
        BASALT_PILLAR = "Ðþ Îä ÑÒ Öù ×Ó",
        HOUNDMOUND = "ÁÔ È® Çð",
        HOUNDBONE = "ÁÔ È® Ê¬ ¹Ç",
        MERM = "Óã ÈË",
        MERMHOUSE = "Óã ×å ·Ï Ðæ",

        MARBLEPILLAR = "´ó Àí Ê¯ Öù ×Ó",
        MARBLETREE = "´ó Àí Ê¯ Ê÷",
        MARBLE = "´ó Àí Ê¯",
        KNIGHT = "·¢ Ìõ Æï Ê¿",
        BISHOP = "·¢ Ìõ Ö÷ ½Ì",
        ROOK = "»ú Ðµ Õ½ ³µ",
        SUNKBOAT = "³Á ´¬",
        MAXWELLPHONOGRAPH = "Âó Ë¹ Íþ ¶û µÄ ÕÕ Æ¬",
        MAXWELLTHRONE = "Ø¬ ÃÎ Íõ ×ù",
        MAXWELLLOCK = "Ø¬ ÃÎ Ëø Í·",

        LOCKEDWES = "Î¤ Ë¹",
        TREASURECHEST_TRAP = "±¦ Ïä ÏÝ Úå",
        MEATRACK = "É¹ Èâ ¼Ü",
        BANDAGE = "·ä ÃÛ Ò© ¸à",
        HEALINGSALVE = "ÖÎ ÁÆ Ò© ·Û",
        CANE = "¼Ó ËÙ ÊÖ ÕÈ",
        LIGHTNING = "ÉÁ µç",
        LIGHTNING_ROD = "±Ü À× Õë",
        DIVININGROD = "Ì½ ²â Ä§ ÕÈ",
        DIVININGRODBASE = "Ä§ ÕÈ ³Ö ÓÐ Õß",
        DIVININGRODSTART = "Ä§ ÕÈ ³Ö ÓÐ Õß",

        SLURTLE = "º¬ ºý ³æ",
        SLURTLESLIME = "ÎÏ Å£ Õ³ Òº",
        SLURTLEHOLE = "º¬ ºý ³æ ÍÁ ¶Ñ",
        SLURTLEHAT = "±³ ¿Ç Í· ¿ø",
        SNURTLE = "ð¤ ºý ³æ",
        SLURTLE_SHELLPIECES = "ÆÆ Ëé µÄ ±³ ¿Ç",
        ARMORSNURTLESHELL = "ð¤ ºý ³æ ¿Ç ¼×",
        MAGIC_BLUEPRINT = "¿Õ °× µÄ Éè ¼Æ Í¼",
        BAT = "ºÚ òù òð",
        TEAMLEADER = "Ð¡ ¶Ó Ê× Áì",
        BATWING = "ºÚ òù òð ³á °ò",
        BATWING_COOKED = "Öó Êì µÄ ºÚ òù òð ³á °ò",
        GUANO = "Äñ Êº",
        LANTERN = "Ìá µÆ",
        POWCAKE = "·Û ¸â",
        FLOWER_CAVE = "Ó« ¹â »¨",
        FLOWER_CAVE_DOUBLE = "Ó« ¹â »¨",
        FLOWER_CAVE_TRIPLE = "Ó« ¹â »¨",
        LIGHTBULB = "Ó« ¹â ¹û",
        STALAGMITE = "Ê¯ Ëñ",
        SPIDERHOLE = "Öë Íø ÑÒ",
        EYEPLANT = "ÑÛ Çò »¨",
        LUREPLANT = "Èâ Çò ¾¥",
        LUREPLANTBULB = "Ê³ ÈË »¨ Çò ¾¥",
        BATBAT = "Îü Ñª òù òð ÈÐ",
        BATCAVE = "òù òð ¶´",
        CAVE_FERN = "Þ§ Àà Ö² Îï",
        FOLIAGE = "Ê÷ Ò¶",
        CAVE_BANANA_TREE = "¶´ Ñ¨ Ïã ½¶ Ê÷",
        CAVE_BANANA = "¶´ Ñ¨ Ïã ½¶",
        CAVE_BANANA_COOKED = "Öó Êì µÄ Ïã ½¶",
        ROCKY = "ÑÒ Ê¯ ´ó Áú Ïº",
        MONKEY = "±© Ôê ºï",
        MONKEYBARREL = "±© Ôê ºï Èº",
        SLURPER = "à¨ Ê³ Õß",
        STAFFLIGHT = "°« ÈË Ã÷ ÐÇ",

        RELIC = "·Ï Ðæ",
        RUINS_RUBBLE = "Ëð »Ù µÄ ·Ï Ðæ",
        MULTITOOL_AXE_PICKAXE = "Õª / ¸« Í·",
        SLURPER_PELT = "à¨ Ê³ Õß Ö® Æ¤",
        THULECITE = "îû ¿ó",
        ARMORRUINS = "îû ¿ó Ç½ ±Ú",
        ARMORSLURPER = "¼¢ ¶ö Ñü ´ø",
        RUINS_BAT = "îû ¿ó °ô",
        LICHEN = "¶´ Ñ¨ Ì¦ Þº",
        CUTLICHEN = "Ì¦ Þº",
        NIGHTMARE_TIMEPIECE = "îû ¿ó ½± ÕÂ",
        BISHOP_NIGHTMARE = "Ëð »µ µÄ Ïó",
        ROOK_NIGHTMARE = "Ëð »µ µÄ Õ½ ³µ",
        KNIGHT_NIGHTMARE = "Ëð »µ µÄ Æï Ê¿",
        MINOTAUR = "Ô¶ ¹Å ÊØ »¤ Õß",
        SPIDER_DROPPER = "Ñ¨ ¾Ó Ðü Öë",
        NIGHTMARELIGHT = "Ó° µÆ",

        THULECITE_PIECES = "îû ¿ó Ê¯ Ëé Æ¬",
        RUINSHAT = "îû ¿ó Ê¯ »Ê ¹Ú",
        POTTEDFERN = "Åè ÔÔ µÄ Þ§ Àà Ö² Îï",
        UNAGI = "÷© Óã ÊÙ Ë¾",
        EEL = "÷© Óã",
        EEL_COOKED = "Êì ÷© Óã",
        EYETURRET = "ºã µÏ ÓÈ Ë¹ ¡¤ Êæ Ìá ÓÈ Ë¹",
        EYETURRET_ITEM = "ºã µÏ ÓÈ Ë¹ ¡¤ Êæ Ìá ÓÈ Ë¹",
        MINOTAURHORN = "ÊØ ÎÀ Õß µÄ ½Ç",
        POND_ALGAE = "Ë® Ôå",
        WORMLIGHT = "·¢ ¹â ½¬ ¹û",

        WORM_PLANT = "Éñ ÃØ µÄ Ö² Îï",
        WORM_DIRT = "Äà ÍÁ ¶Ñ",
        WORM = "Éî Ô¨ Èä ³æ",

        MOSQUITOSACK = "ÎÃ ×Ó ´ü",
        LIVINGTREE = "Íê È« Õý ³£ µÄ Ê÷",

        WAXWELLJOURNAL = "°µ Ó° Ä§ ·¨ Êé",
        SHADOWWAXWELL = "Ó° ×Ó ¿þ ÀÜ",

        ACCOMPLISHMENT_SHRINE = "¿¨ ÆÕ Ê· ¶÷ ½± ±­",

        NIL = "ºÚ °µ",
        DARKNESS = "ºÚ °µ",
        CHARLIE = "²é Àí",
        HUNGER = "¼¢ ¶ö",
        COLD = "Àä ¶³",
        HOT = "¹ý ÈÈ",
        SHENANIGANS = "¶ñ ×÷ ¾ç",
        RESURRECTION_PENALTY = "¸´ »î ºò Ö¢ Èº",

        UNKNOWN = "Î´ Öª",

        BEARGER = "ÐÜ âµ",
        BIGFOOT = "¾Þ ´ó µÄ ½Å",

        SPEAR_WATHGRITHR = "Õ½ Õù Ö® Ã¬",
        WATHGRITHRHAT = "Õ½ Õù Ö® ¿ø",

        MOOSE1 = "Ä½ Ë¹ ¶ì",
        MOOSE2 = "¶Ç Ë¹ Â¹",
        MOOSEEGG1 = "Ä½ Ë¹ ¶ì µÄ µ°",
        MOOSEEGG2 = "¶Ç Ë¹ Â¹ µÄ µ°",
        MOOSENEST1 = "Ä½ Ë¹ ¶ì µÄ ³²",
        MOOSENEST2 = "¶Ç Ë¹ Â¹ µÄ ÎÑ",
        MOSSLING = "Ð¡ Ë¹ ¶ù",
        WINTEROMETER = "ÎÂ ¶È Ö¸ Ê¾ ¼Æ",
        BIRCHNUTDRAKE = "±´ ¶û ¡¤ ÄÉ ÌØ",
        DECIDUOUSTREE = "±´ ¶û ¡¤ ÄÎ Ê÷",
        DECIDUOUS_ROOT = "Æø ·ß µÄ ±´ ¶û ¡¤ ÄÎ Ê÷", --This is never used in game: this is for morgue screen (deaths by root)
        ACORN = "±´ ¶û ¡¤ Ïð ¹û",
        ACORN_SAPLING = "±´ ¶û ¡¤ ÄÎ Ê÷ Ê÷ Ãç",

        GLOMMER = "¸ñ À­ ²® ³æ",
        GLOMMERFLOWER = "¸ñ À­ ²® »¨",
        GLOMMERWINGS = "¸ñ À­ ²® ³á °ò",
        GLOMMERFUEL = "¸ñ À­ ²® Õ³ Òº",
        STATUEGLOMMER = "¸ñ À­ ²® µñ Ïñ",

        CACTUS = "ÏÉ ÈË Çò",
        CACTUS_MEAT = "ÏÉ ÈË Çò Èâ",
        LIGHTNINGGOAT = "·ü ÌØ Ñò",
        BUZZARD = "Íº ðÕ",

        DRAGONFLY = "òß òÑ",
        LAVASPIT = "òß òÑ ÍÙ Òº",

        RAINCOAT = "Óê ÒÂ",
        RAINHAT = "·À Óê Ã±",
        GRASS_UMBRELLA = "Æ¯ ÁÁ µÄ »¨ É¡",
        ICEHAT = "Ò» ´ó ¿é ±ù",
        MOLEHAT = "Èä Êó µÄ ÑÛ ¾¦",
        TRANSISTOR = "µç ×Ó ¾§ Ìå ¹Ü",
        LIGHTNINGGOATHORN = "·ü ÌØ Ñò ½Ç",
        MOLE_UNDERGROUND = "Í¹ Æð µÄ Äà ÍÁ",
        MOLE_ABOVEGROUND = "Èä Êó",
        MOLE = "Èä Êó",
        MOLEHILL = "µØ ¶´",
        BONESHARD = "¹Ç Í· Ëé Æ¬",

        FERTILIZER = "Ò» ´ó Í° ±ã ±ã ·Ê ÁÏ",
        FIRESUPPRESSOR = "ÖÆ Àä »ú",
        CACTUS_MEAT_COOKED = "¿¾ ÏÉ ÈË ÕÆ Æ¬",
        ACORN_COOKED = "½¬ ¿¾ ±´ ¶û ¡¤ Ïð ¹û",
        WEBBERSKULL = "Î¤ ²® µÄ Í· ¹Ç",

        WATERMELON = "Î÷ ¹Ï",
        WATERMELON_COOKED = "ÑÒ ¿¾ Î÷ ¹Ï",
        WATERMELONHAT = "Çå Ë¬ Î÷ ¹Ï Ã±",        
        CATCOONHAT = "¿â ¶÷ Ã¨ ¶¬ Óê Ã±",
        CATCOON = "¿â ¶÷ Ã¨",
        CATCOONDEN = "¿Õ ÐÄ Ê÷ ×®",
        BELL = "Ô¶ ¾Ã µÄ ÖÓ",

        WARG = "ÁÔ ÀÇ",

        BEARGERVEST = "ÐÜ âµ Ã« ÑÏ ¶¬ ±³ ÐÄ",
        ARMORDRAGONFLY = "»ð ÁÛ ¼×",
        EYEBRELLA = "¾Þ É¡",
        FEATHERFAN = "Çå Ë¬ Óð Ã« ÉÈ",
    },

    DIRECTIONS=
    {
        N = "±±",
        S = "ÄÏ",
        E = "¶«",
        W = "Î÷",
        NE = "¶« ±±",
        SE = "¶« ÄÏ",
        NW = "Î÷ ±±",
        SW = "Î÷ ÄÏ",
    },
    
    RECIPE_DESC=
    {

        BOOK_BIRDS = "°ü À¨ 1000 ¸ö Îï ÖÖ £º Ï° ÐÔ £¬ ÆÜ Ï¢ µØ ºÍ ºô »½ ¡£",
        BOOK_TENTACLES = "ÈÃ ÎÒ ÃÇ ÁË ½â Ò» ÏÂ ÎÒ ÃÇ µØ ÏÂ µÄ Åó ÓÑ £¡",
        BOOK_GARDENING = "ÕÕ ÁÏ Î¹ Ñø Ö² Îï ¡£",
        BOOK_SLEEP = "¸§ Î¿ µÄ ¹Ê ÊÂ ´ø Èë ÃÎ ¾³ ¡£",
        BOOK_BRIMSTONE = "ÊÀ ½ç ½« »Ù ÓÚ ÉÁ µç Óë »ð ÄÑ £¡",

        COMPASS = "Ö¸ Ïò ±± ±ß",
        GUNPOWDER = "Ò» °Ñ ¼´ ÓÃ µÄ »ð Ò©",
        TORCH = "ÊÖ Ìá ¹â Ô´",
        TRAP = "ÓÃ À´ ²¶ »ñ µØ ÉÏ µÄ Ð¡ Éú Îï",
        BIRDTRAP = "²¶ »ñ Äñ Àà µÄ ÏÝ Úå",
        PIGHOUSE = "×¡ ×Å Ò» Ö» Öí ÈË",
        RABBITHOUSE = "×¡ ×Å Ò» Ö» ¾Þ ´ó ÍÃ ×Ó ºÍ ¹î Òì ÍÃ ×Ó ¶« Î÷",
        CAMPFIRE = "È¼ ÉÕ Ê± ÄÜ ¹» ·¢ ¹â ºÍ ±£ Å¯",
        FIREPIT = "¸ü °² È« ¸ß Ð§ µÄ óô »ð",
        COLDFIRE = "Õâ Ò» Ìì ÊÔ ÊÔ Íê È« Ïà ·´ µÄ »ð Ñæ",
        COLDFIREPIT = "¸ü ¸ß Ð§ £¬ µ« ÈÔ È» »¹ ²» ÊÇ ×î ºÃ µÄ",
        FIRESUPPRESSOR = "±£ ´æ Ö² Îï £¬ ½µ µÍ ÎÂ ¶È £¬ Ôù Óè »ð µÄ Àñ Îï",
        FERTILIZER = "Ò» µã ±ã ±ã ÔÚ ÊÖ £¬ Ìì ÏÂ Ö² Îï ¶¼ ÓÐ",
        HEATROCK = "Îª ÂÃ ÐÐ ´¢ ´æ ÈÈ Á¿",
        SLOW_FARMPLOT = "ÓÃ ÖÖ ×Ó ÖÖ Ö² Å© ×÷ Îï",
        FAST_FARMPLOT = "¸ü ¿ì ³¤ ³ö Å© ×÷ Îï",
        TENT = "»Ø ¸´ ¾« Éñ ºÍ Ìå Á¦ £¬ µ« Ïû ºÄ Ê± ¼ä Óë ¼¢ ¶ö ¶È",
        SIESTAHUT = "±Ü ¿ª °× Ìì µÄ Ñ× ÈÈ £¬ »Ö ¸´ ¸ü ºÃ µÄ ¾« Éñ",
        ROPE = "ÓÉ ²Ý ±à Ö¯ ³É µÄ Éþ Ë÷",
        ARMORWOOD = "±£ »¤ Äã Ãâ ÓÚ ÊÜ ÉË",
        ARMORGRASS = "Ìá ¹© ÉÙ Á¿ ±£ »¤",
        ARMORMARBLE = "Ëä È» ºÜ ÖØ £¬ µ« Ëü ¿É ÒÔ ¸ü ºÃ µÄ ±£ »¤ Äã",
        ARMOR_SANITY = "±£ »¤ Äã µÄ Çû Ìå £¬ µ« ÎÞ ·¨ ±£ »¤ Äã µÄ ÐÄ ÖÇ",
        SPEAR= "ÓÃ ¼â µÄ Ò» ¶Ë",
        STRAWHAT = "°ï Öú Äã ±£ ³Ö Á¹ Ë¬ ºÍ ¸É Ôï",
        TOPHAT = "×î ÓÐ Æ· Î» µÄ Ã± ×Ó",
        FLOWERHAT = "»Ø ¸´ ¾« Éñ",
        BEEFALOHAT = "±ä ³É ÁË Ò» Í· Å£ £¡ »¹ ÓÐ ¹É Å£ µÄ Î¶ µÀ",
        AXE = "¿³ µ¹ Ê÷ Ä¾ £¡",
        PICKAXE = "´ò Ëé ÑÒ Ê¯",
        HAMMER = "ÆÆ »µ ¸÷ ÖÖ ¸÷ Ñù µÄ ¶« Î÷",
        SHOVEL = "ÍÚ ³ö ¸÷ ÖÖ ¸÷ Ñù µÄ ¶« Î÷",
        PITCHFORK = "ÒÆ ¶¯ ÍÁ µØ ±í Æ¤",
        GOLDENAXE = "·ç É§ µØ ¿³ µ¹ Ê÷ Ä¾ °É £¡",
        GOLDENPICKAXE = "¸ú Boss Ò» Ñù ´ò Ëé Ê¯ Í·",
        GOLDENSHOVEL = "ÄÍ ¾Ã ¸ü ¸ß £¬ µ« ÍÚ ³ö À´ µÄ ¶« Î÷ ¶¼ Ò» Ñù",
        GOLDENPITCHFORK = "ÖØ ÐÂ °² ÅÅ Õâ ¸ö ÊÀ ½ç",
        CUTSTONE = "±ê ×¼ Á¢ ·½ ÐÎ Ê¯ Í·",
        WINTEROMETER = "²â Á¿ ÖÜ Î§ ¿Õ Æø ÎÂ ¶È",
        RAINOMETER = "¿´ ¿´ ½µ Óê µÄ ¿É ÄÜ ÐÔ",
        RESURRECTIONSTATUE = "ÓÃ Èâ µÄ Á¦ Á¿ Ê¹ Äã ¸´ Éú",
        BOARDS = "Àà ËÆ Ô­ Ä¾ £¬ µ« ÊÇ ¸ü Îª Æ½ Õ¹",
        RESEARCHLAB = "½â Ëø ÐÂ µÄ ¿Æ ¼¼ Çå µ¥ £¡",
        BACKPACK = "ÄÜ Ð¯ ´ø ¸ü ¶à Îï Æ·",
        PIGGYBACK = "ÄÜ Ð¯ ´ø Ðí ¶à Îï Æ· £¬ µ« ÊÇ »á ½µ µÍ Äã µÄ ÒÆ ¶¯ ËÙ ¶È",
        UMBRELLA = " Áô ×Å Ñ× ÈÈ ºÍ Óê Ë® ÔÚ Ìì ÉÏ £¡ ",
        RESEARCHLAB2 = "½â Ëø ¸ü ¶à ¿Æ ¼¼ Çå µ¥ £¡",
        RESEARCHLAB3 = "¸ü ¶à µÄ Ä§ Á¦ £¬ Õâ »¹ Ëã ÊÇ ¿Æ Ñ§ Âð ?",
        RESEARCHLAB4 = "Ôö Ç¿ ²¢ »ñ È¡ ÄÇ ¶¥ Ã± ×Ó µÄ Éñ Ææ Ä§ Á¦",
        RAZOR = "Ìê µô Ôà Ùâ Ùâ µÄ Âç Èù ºú »ò Ã«",
        PAPYRUS = "¿É ÒÔ ÓÃ À´ Êé Ð´",
        PANFLUTE = "¸§ Î¿ ¿ñ Å­ Ò° ÊÞ µÄ Òô ÀÖ",
        COOKPOT = "Ê¹ Ê³ Îï ¸ü ÃÀ Î¶",
        BUGNET = "×¥ ³æ ×Ó",
        BEEBOX = "´¢ ´æ Äã ×Ô ¼º µÄ ÃÛ ·ä",
        BEEHAT = "±£ »¤ Äã µÖ Óù ·¢ ¿ñ ÃÛ ·ä µÄ ¹¥ »÷",
        TREASURECHEST = "Ò» ¸ö ¼á ¹Ì µÄ ÈÝ Æ÷",
        BEDROLL_STRAW = "Çá ËÉ Êæ ÐÄ µØ Ë¯ Ò» Õû Íí",
        BEDROLL_FURRY = "Êæ Êæ ·þ ·þ Ë¯ ¹ý Ò» Ò¹ £¡",
        PUMPKIN_LANTERN = "¹í »ð °ã µÄ ÕÕ Ã÷",
        FISHINGROD = "È¥ µö Óã ¡£ Îª ÁË Óã",
        FEATHERHAT = "¸ø Äã µÄ ÄÔ ´ü ×° °ç Ò» ÏÂ",
        MINERHAT = "ÈÃ ¿ó ¹¤ µÃ ÒÔ ¿Õ ³ö Ë« ÊÖ",
        FOOTBALLHAT = "±£ »¤ Äã µÄ ÄÔ ¿Ç",
        BLOWDART_SLEEP = "ÈÃ Äã µÄ µÐ ÈË »è »è Óû Ë¯",
        BLOWDART_FIRE = "Ïò Äã µÄ µÐ ÈË Åç Éä »ð Ñæ",
        BLOWDART_PIPE = "ÓÃ Àû ³Ý Éä É± Äã µÄ µÐ ÈË",
        BEEMINE = "×ö Îä Æ÷ ÓÃ µÄ ÃÛ ·ä £¬ ÄÇ ÓÐ Ê² Ã´ ÎÊ Ìâ £¿",
        AMULET = "±£ »¤ Äã Ô¶ Àë ËÀ Íö",
        PURPLEAMULET = "Òý Æð ¾« Éñ ´í ÂÒ",
        BLUEAMULET = "ºÃ Àä µÄ »¤ Éí ·û",
        ORANGEAMULET = "Îª ÁË ÄÇ Ð© ²» Ï² »¶ ¼ñ ¶« Î÷ µÄ ÈË",
        GREENAMULET = "ÓÐ ÐÄ ÄÜ Ê¹ ²Ä ´ò ÕÛ £¡",
        YELLOWAMULET = "´Ó Ìì ¿Õ »ñ µÃ Á¦ Á¿",
        SWEATERVEST = "Í¹ Ò» ¿é ¶ù °¼ Ò» ¿é ¶ù £¬ µ« ÊÇ ÓÐ ·¶ ¶ù",
        TRUNKVEST_SUMMER = "ÎÂ Å¯ £¬ µ« ÊÇ Ò² ²» ÌØ ±ð ÎÂ Å¯",
        TRUNKVEST_WINTER = "×ã ÒÔ µÖ µ² ¶¬ Ìì ±© Ñ© µÄ ÎÂ Å¯ ±³ ÐÄ",
        BIRDCAGE = "Äã Äñ Àà Åó ÓÑ µÄ ÀÖ Ô°",
        SPIDERHAT = "Ö© Öë ¶¼ »á º° Äã ¡° Âè Âè ¡±",
        TRAP_TEETH = "Í» È» ³ö ÏÖ £¬ Ôú »® ²È ÔÚ ÉÏ Ãæ µÄ ÈÎ ºÎ ¼Ò »ï",
        TRAP_TEETH_MAXWELL = "Í» È» ³ö ÏÖ £¬ Ôú »® ²È ÔÚ ÉÏ Ãæ µÄ ÈÎ ºÎ ¼Ò »ï",
        EARMUFFSHAT = "Ò» µã ëü ëÊ µÄ ÎÂ Å¯",
        WINTERHAT = "ÈÃ Äã µÄ Í· ²¿ ±£ ³Ö ÎÂ Å¯",
        BUSHHAT = "ºÜ ºÃ µÄ ²Ø Éí ´¦£¡",
        BOOMERANG = "À´ ×Ô ÄÏ ·½ ´ó Â½",
        ICEBOX = "¼õ »º Ê³ Îï ¸¯ °Ü",
        ONEMANBAND = "×î ·è ¿ñ µÄ Òô ÀÖ ¼Ò Ò² ÄÜ Îü Òý ×· Ëæ Õß",
        NIGHTMAREFUEL = "Ð° ¶ñ ²Ð Ôü µÄ Ê¹ ÓÃ À´ ×Ô ÃÔ ÐÅ Óë ·è ¿ñ",
        PURPLEGEM = "×é ºÏ Äã ÃÇ µÄ ÑÕ É« £¡",
        HAMBAT = "ÓÃ Ê³ Îï ÁÔ ²¶ Ê³ Îï",
        HOMESIGN = "ÔÚ È« ÊÀ ½ç ¶¼ Áô ÏÂ Äã µÄ Ó¡ ¼£",
        WALL_WOOD_ITEM = "Ä¾ Ç½ Æ¬ ¶Î",
        WALL_STONE_ITEM = "Ê¯ Ç½ Æ¬ ¶Î",
        WALL_HAY_ITEM = "¸É ²Ý Ç½ Æ¬ ¶Î ¡£ ²» Ì« ½á Êµ",
        TURF_WOODFLOOR = "ÓÅ ÖÊ ½º ºÏ µØ °å",
        TURF_CHECKERFLOOR = "¹æ Ôò ·½ ¸ñ ´ó Àí Ê¯ ´É ×©",
        TURF_CARPETFLOOR = "³¬ Èá Èí ¡£ ÎÅ Æð À´ ºÃ Ïñ Æ¤ ¸¥ Â¦ Å£",
        TURF_ROAD = "½« Äã ×Ô ¼º µÄ µÀ Â· ¿ª ±Ù µ½ ÈÎ ºÎ µØ ·½",
        SEWING_KIT = "ÐÞ Àí ÆÆ Ëð µÄ ÒÂ Îï",
        NIGHTLIGHT = "ÓÃ Äã µÄ ÃÎ µã ÁÁ Ò¹ Íí",
        NIGHTSWORD = "·è ¿ñ Óë ·è ¿ñ µÄ ÉË º¦",
        ICESTAFF = "¶³ ½á Â· ÉÏ µÄ µÐ ÈË",
        FIRESTAFF = "Àû ÓÃ È¼ ÉÕ µÄ Á¦ Á¿ £¡",
        MEATRACK = "×î ´Ö Â³ µÄ Åë µ÷ ·½ Ê½",
        BANDAGE = "ÖÎ ÁÆ Äã µÄ ÉË ¿Ú",
        HEALINGSALVE = "Îª ¸î ÉË ºÍ ²Á ÉË Ïû ¶¾",
        LIGHTNING_ROD = "µÖ Óù À× »÷",
        CANE = "Ãô ½Ý µÄ ²½ ·¥ Óë ÓÅ Òì µÄ Æ½ ºâ",
        DIVININGROD = "¿Ï ¶¨ ÓÐ °ì ·¨ ÄÜ Àë ¿ª Õâ Àï µÄ ¡­¡­", 
        LANTERN = "¿É ÒÔ Ìî ×° È¼ ÁÏ £¬ ºÜ Ã÷ ÁÁ £¬ »¹ ±ã ÓÚ Ð¯ ´ø",
        BATBAT = "Ëù ÓÐ µÄ ¿Æ ¼¼ Ïû ºÄ ¶¼ Õâ Ã´ ¡­¡­ ´ó",
        TELESTAFF = "Å¤ Çú ¿Õ ¼ä £¡ Ê± ¼ä Å¤ Çú µ¥ ¶À ÊÛ Âô",
        ORANGESTAFF = "Îª ÄÇ Ð© ²» Ï² »¶ ×ß Â· µÄ ÈË",
        GREENSTAFF = "¸É ¾» ÓÐ Ð§ µÄ ÆÆ »µ",
        YELLOWSTAFF = "ÕÙ »½ Ò» ¸ö Ð¡ ÐÇ ÐÇ",
        TELEBASE = "Ö» Ðè Ìí ¼Ó ±¦ Ê¯",
        MULTITOOL_AXE_PICKAXE = "Ë« ÖØ ×÷ ÓÃ",
        ARMORRUINS = "ÉÁ ÉÁ µÄ »¹ ¾ß ÓÐ ±£ »¤ ÐÔ",
        RUINS_BAT = "³¤ ¶¤ ÈÃ Ëù ÓÐ µÄ ¶« Î÷ ¶¼ ±ä µÃ ¸ü ºÃ",
        NIGHTMARE_TIMEPIECE = "×· ×Ù ÖÜ Î§ Ä§ ·¨ µÈ ¼¶ µÄ Ë¥ Âä ºÍ Á÷ ¶¯",
        ARMORSLURPER = "±£ ³Ö ±¥ Âú µÄ ¶Ç ×Ó",
        EYETURRET_ITEM = "°Ñ Õâ Ð© ¶ñ ÐÄ µÄ ¶« Î÷ ÄÃ ¿ª ¡£ Òª ±» Ëü ÃÇ É± ËÀ ÁË",
        ACCOMPLISHMENT_SHRINE = "Ö¤ Ã÷ Äã µÄ ¼Û Öµ Èç ½± ±­ °ã ÉÁ Ò«",
        WALL_RUINS_ITEM = "Õâ Ð© Î§ Ç½ ºÜ ÄÍ ´ò",
        POTTEDFERN = "×ö Ò» ¸ö »¨ Åè ºÍ ÒÑ ÖÖ ºÃ µÄ Þ§ Àà Ö² Îï",
        THULECITE = "°Ñ Ò» Ð© Ð¡ ¿é µÄ îû ¿ó Ê¯ ÈÜ ³É Ò» ´ó ¿é",
        RUINSHAT = "¸´ Ô­ Ô¶ ¹Å »Ê ¹Ú µÄ ±£ »¤ Á¦ Á¿ £¡",

        RAINCOAT = "Ò» ¼þ ·À Ë® Óê ÒÂ ¿É ÒÔ ÈÃ Äã ±£ ³Ö ¸É Ôï",
        RAINHAT = "Óê Ã± Èá Èí ºÃ ÎÕ £¬ Óê µÎ Çá »¬ ¶ø ¹ý",
        GRASS_UMBRELLA = "ºÃ ¿´ ¡¢ ºÃ ¾« Ð¡ ¡¢ ºÃ Íê Õû µÄ É¡",

        SPEAR_WATHGRITHR = "»Æ½ðµÄÁ¦Á¿ÈÃËü¸ü¼Ó¹âÒ«",
        WATHGRITHRHAT = "½ð÷è÷ëÊØ»¤×ÅÄãµÄÉúÃü",

        MOLEHAT = "ÊÚ Óè Åå ´÷ Õß 5D µÄ ÄÜ Á¦",
        ICEHAT = "¿Æ Ñ§ £¬ ¾Í ÊÇ Ê¯ Í·",
        TRANSISTOR = "¿Æ ¼¼ ±ð ²ø ×Å ÎÒ £¡ àÛ ×È £¡",
        
        WATERMELONHAT = "Á¹ Ë¬ £¬ µ« ÓÐ µã ð¤ ð¤",

        BELL = "Õâ ²» ½ö ½ö ÊÇ ¸ö ÖÓ",

    },

    -- MAXWELL_TEST = {"Say pal, you don't look so good.", "You better find something to eat before night comes!"},

    -- MAXWELL_QUEST_SURVIVE = {
    --  {"Say pal, you don't look so good.", "You better find something to eat before night comes!"},
    --  {"Say pal, you don't look so good.", "You have some space to explore methinks."},
    --  {"This may take some time...", "Don't get lost now!"},
    --  {"The dew has fallen with a particularly sickening thud this morning...", "I'm off to find Zem..."},
    --  {"Lucky nothing uses water eh?", "Its going to be a long day"},
    --  {"Don't forget your booties cause its cold out there!", "Its cold out there every day."},
    --  {"Safe and secure area?", "Its just a skip, hop and a jump away from here."},
    --  {"Say pal, keep your chin up.", "You will probably find it hard to stay dapper."},
    --  {"I left you a little something...","I don't think it will help you though.", "You know what I like about nighttime?", "All the spiders."},
    --  },      

    MAXWELL_SANDBOXINTROS = 
    {
        ONE = "Î¹ ! Åó ÓÑ £¬ Äã ¿´ ÉÏ È¥ ×´ Ì¬ ²» ¼Ñ ",
        TWO = "Äã ×î ºÃ ÔÚ Ò¹ Íí À´ ÁÙ Ç° ÕÒ µã ³Ô µÄ £¡ ",       
    },

   MAXWELL_ADVENTUREINTROS =
    {
        LEVEL_1 =
        {
            ONE = "àÞ £¬ Äã ÕÒ µ½ ÎÒ µÄ ´« ËÍ ÃÅ ÁË ¶Ô °É £¿ ",
            TWO = "Äã »á ¾õ µÃ Äã ÏÖ ÔÚ ÓÐ µã ³¤ ½ø ÁË",
            --THREE = "Strange machinery hasn't exactly been kind to you in the past.",
            THREE = "àÅ ¡£ÎÒ ÃÇ À´ ÊÔ Ò» Ð© ¸ü ÓÐ Ìô Õ½ ÐÔ µÄ £¬ ºÃ Âð £¿ ",
            --FIVE = "Let's see if you're so enthusastic when it's fourty below.",
        },
        LEVEL_2 =
        {
            ONE = "Äã ºÃ ºÃ ¿´ ×Å £¬ Äã »î ÁË ÏÂ À´ ",
            TWO = "¸ã ¶¨ Ò» ¸ö £¬ »¹ ÓÐ ËÄ ¸ö £¡ ",
            --TWO = "Now don't get a big head, you aren't the first.",
            --THREE = "Let's see what you're really made of.",
            --FOUR = "And by that I mean to say,",
            --FIVE = "I will enjoy inspecting your entrails once the Deerclops is done with you.",
        },
        LEVEL_3 =
        {
            ONE = "Ê² Ã´ £¿ Äã »¹ ÔÚ Õâ ¶ù £¿ ",
            TWO = "²» ´í ¡£µ« ÊÇ Äã ÔÚ Ç° Ãæ µÄ Ê± ºò Ó¦ ¸Ã Í£ ÏÂ À´ ",
            --TWO = "Must I do everything myself?",
            --THREE = "HOUNDS! DISPOSE OF THIS PEST!",
        },
        LEVEL_2 =
        {
            ONE = "Äã ºÃ ºÃ ¿´ ×Å £¬ Äã »î ÁË ÏÂ À´ ",
            TWO = "¸ã ¶¨ Ò» ¸ö £¬ »¹ ÓÐ ËÄ ¸ö £¡ ",
            --TWO = "Now don't get a big head, you aren't the first.",
            --THREE = "Let's see what you're really made of.",
            --FOUR = "And by that I mean to say,",
            --FIVE = "I will enjoy inspecting your entrails once the Deerclops is done with you.",
        },
        LEVEL_3 =
        {
            ONE = "Ê² Ã´ £¿ Äã »¹ ÔÚ Õâ ¶ù £¿ ",
            TWO = "²» ´í ¡£µ« ÊÇ Äã ÔÚ Ç° Ãæ µÄ Ê± ºò Ó¦ ¸Ã Í£ ÏÂ À´ ",
            --TWO = "Must I do everything myself?",
            --THREE = "HOUNDS! DISPOSE OF THIS PEST!",
        },
        LEVEL_4 =
        {
            ONE = "ºÙ £¬ Åó ÓÑ ",
            TWO = "Äã Õæ ÊÇ ºÜ ÐÒ ÔË °¡ ",
            THREE = "ÏÖ ÔÚ ¸ø ÎÒ »Ø È¥ £¬ ·ñ Ôò ÎÒ ¾Í Òª ÓÃ ·Ç ³£ ÊÖ ¶Î ÁË °¡ ",
        },
        TWOLANDS =
        {
            ONE = "ºÙ £¬ Åó ÓÑ ",
            TWO = "ÎÒ ÃÇ À´ ×ö ¸ö ½» Ò× ¡£Äã ¿É ÒÔ ´ý ÔÚ Õâ £¬ Éõ ÖÁ ¶¨ ¾Ó ÏÂ À´ ",
            THREE = "ÎÒ ½« ¸ø Äã Ê³ Îï £¬ ½ð ×Ó ºÍ Öí ¡­¡­ Äã Ëù Ðè Òª µÄ Ò» ÇÐ ",
            FOUR = "ÎÒ Ïë Òª µÄ »Ø ±¨ Ö» ÊÇ Ò» ·Ý Í£ Õ½ Ð­ ¶¨ ",
        },
        LEVEL_5 =
        {
            ONE = "Äã Õâ ¸ö °Á Âý ¡¢ÎÞ Öª ¡¢¿É Á¯ µÄ Âì ÒÏ £¡ ",
            TWO = "²» Òª ¼¤ Æð Î° ´ó Âó Ë¹ Íþ ¶û µÄ ·ß Å­ ",
            THREE = "ÔÙ ¿¿ ½ü Ò» ²½ Äã »á ºó »Ú µÄ ¡­¡­",
        },
        LEVEL_6 =
        {
            ONE = "ºÃ °É £¬ ¾Í ÊÇ Õâ Ñù ",
            TWO = "Äã ÕÒ µ½ ÎÒ ÁË ¡£ÏÖ ÔÚ £¬ Äã ´ò Ëã Ôõ Ã´ °ì £¿ ",
            TELEPORTFAIL = "Äã ²» ¾õ µÃ ÎÒ ÒÑ ¾­ ÊÔ ¹ý ÁË £¿ ",
            TELEPORTFAIL2 = "Íê ÁË ¡£ÎÒ ÃÇ Ã» ÓÐ ³ö Â· ÁË ",
            COMBATFAIL = 
            {
                "ÄÇ ÓÖ Ôõ Ã´ Ñù £¿ ",
                "Ë­ ÔÊ Ðí Äã Õâ Ã´ ×ö µÄ £¿ ",
            },
            CONVERSATION = 
            {
                "Õâ ¾Í ÊÇ Äã Ïë Òª µÄ £¿ ",
                "ÎÒ Òª ÊÇ Æð ²» À´ ÁË £¬ ¾Í °Ñ ÎÒ Íü ÁË °É ",
                "Äã Õý Íæ µÃ ºÜ ¿ª ÐÄ £¬ µ« ÎÒ ÒÑ ¾­ ÓÐ µã Ñá ¾ë Õâ ÓÎ Ï· ÁË ",
                "»ò Õß ÊÇ Ëû ÃÇ Ñá ¾ë ÎÒ ÁË ",
                "ºß ¡£Ëû ÃÇ ÓÃ ÁË ºÜ ³¤ Ê± ¼ä ",
                "Ëû ÃÇ »á ÈÃ Äã ¿´ µ½ ¿É ÅÂ ÓÖ ÃÀ Àö µÄ ¶« Î÷ ",
                "Ëû »á ¸Ä ±ä Äã £¬ ¾Í Ïñ ¸Ä ±ä ÎÒ Ò» Ñù ",
                "×î ºÃ ±ð ·´ ¿¹ ",
                "ÎÒ À´ µÄ Ê± ºò ÒÑ ¾­ Ã» ÓÐ Ê² Ã´ ÁË ",
                "Ö» ÓÐ ³¾ °£ £¬ Ðé ¿Õ £¬ »¹ ÓÐ Ëû ÃÇ ",
                "´Ó ´Ë ÎÒ Ñ§ »á ÁË ºÜ ¶à ¡£ÎÒ ³¤ ´ó ÁË ",
                "µ« ¼´ Ê¹ ÊÇ ¹ú Íõ Ò² ÎÞ ÄÜ Îª Á¦ ",                
                "Äã ÎÞ ·¨ ¸Ä ±ä ÓÎ Ï· ¹æ Ôò ",
                "ÎÒ ²» Öª µÀ Ëû ÃÇ Òª Ê² Ã´ ¡£Ëû ÃÇ ¡­¡­ Ëû ÃÇ Ö» ÊÇ ¿´ ×Å ",
                "³ý ·Ç Äã ¿¿ µÃ Ì« ½ü £¬ È» ºó ¡­¡­",
                "°¡ £¬ ÓÐ Ò» ¸ö Ô­ Òò ÈÃ ÎÒ ±£ ³Ö Çå ÐÑ ",
                "ÄÇ Àï ÊÇ ÄÄ Äê À´ ×Å £¿ Õâ Àï µÄ Ê± ¼ä ÓÐ Ð© ²» Ò» Ñù ",
                "¼Ì Ðø £¬ ´ý Ò» »á ¶ù ¡£Åã Åã ÎÒ ÃÇ ",
                "»ò Õß °Ñ Ô¿ ³× ·Å µ½ Ïä ×Ó Àï ¡£Äã À´ ¾ö ¶¨ ",
                "ÎÞ ÂÛ Èç ºÎ £¬ Äã Ö» ÊÇ ÔÚ ÍÏ ÑÓ ±Ø ½« ·¢ Éú µÄ ÊÂ Çé ",
                "ÓÐ Ê± £¬ ÏÖ Êµ ¾Í ÊÇ ÄÇ Ñù ",
                "ÎÒ Ïë ÎÒ Ëµ µÄ ¹» ¶à ÁË ",
                "...",
            },
        },

    },

    MAXWELL_ADVENTURE_HEAD =
    {
        LEVEL_4 =
        {
            ONE = "ºÃ °É ¡£ ¼Ç ×¡ £¬ Õâ ÊÇ Äã Ñ¡ µÄ",
        },
        LEVEL_6 =
        {
            ONE = "ÎÒ ºÍ Äã ²¢ Ã» ÓÐ ¶à ÉÙ ²» Í¬",
            TWO = 
            {
                ONE = "ÄÇ ¾Í ÊÇ ÎÒ °Ñ Äã ´ø µ½ Õâ ¶ù µÄ Ô­ Òò ",
                TWO = "ÄÇ ¾Í ÊÇ ÎÒ °Ñ Ëû ÃÇ Ëù ÓÐ ÈË ´ø µ½ Õâ ¶ù µÄ Ô­ Òò ",
            },
            THREE =   
            {
                ONE = "Å¶ £¬ Äã ÒÔ Îª Äã ÊÇ µÚ Ò» ¸ö £¿",
                TWO = "¹þ £¡",
            },
            FOUR = 
            {
                ONE = "Ö» ÊÇ ¡­¡­",
                TWO = "ÎÒ ÒÑ Ï° ¹ß ÓÚ »ñ Ê¤",
            },
        },
    },

    MAXWELL_ADVENTURETHRONE =
    {
        LEVEL_6 =
        {
            INTRO =
            {
                ONE = "Õâ ¾Í ÊÇ ½á ¾Ö £¿ ",
            },
            HIT =
            {
                ONE = "Íõ ×ù ²» »á ÈÃ Äã ÄÇ Ñù ¡£ÎÒ ÀÛ ÁË",
            },
            NOUNLOCK =
            {
                ONE = "°¡ £¬ ÎÒ ÊÇ ¸ö Éµ ¹Ï ¡£ÎÒ ¾¹ È» »³ ÓÐ Ï£ Íû",
            },
            PHONOGRAPHON =
            {
                ONE = "ÎÒ Ïë ÄÇ ÊÇ ÎÒ Ó¦ µÃ µÄ ",
            },
            PHONOGRAPHOFF =
            {
                ONE = "Ð» Ð» Äã £¬ ÎÒ Ò» Ö± Ìý ×Å ÄÇ Ê× ¸è ",
            },
        },
    },
    
    --ITEM DESCRIPTIONS
    DESCRIBE_NULL = "È± Ê§ Ãè Êö ×Ö ·û ´® ",


    PIG_TALK_FOLLOWWILSON = {"Åó ÓÑ ", "Öí ÈË Ï² »¶ Åó ÓÑ ", "Äã Õæ ºÃ ", "Öí ÈË ¸ú ×Å £¡"},
    PIG_TALK_FIND_LIGHT = {"ºÃ ¿É ÅÂ ", "Öí ÈË ²» Ï² »¶ ºÚ °µ ", "Ì« Ñô ÔÚ ÄÄ Àï £¿ ", "´ý ÔÚ »ð ¶Ñ ÅÔ ", "»ð ×Ü ÊÇ ºÃ µÄ "},
    PIG_TALK_LOOKATWILSON = {"Äã ÊÇ Ë­ £¿", "Äã ²» ÊÇ Öí ", "³ó Âª µÄ ºï ×Ó ÈË ", "Äã ³Ô Èâ £¿"},
    PIG_TALK_RUNAWAY_WILSON = {"Ì« ½ü ÁË £¡ ", "¹ö ¿ª £¡ ", "Äã ÍË ºó £¡ ", "ÄÇ ÊÇ ÎÒ µÄ µØ ÅÌ "},
    PIG_TALK_FIGHT = {"Öí ÈË ÏÖ ÔÚ ¾Í ¿ª É± ½ä £¡ ", "Äã Íê µ° ÁË £¡ ", "°¡ °¡ °¡£¡ "},
    PIG_TALK_RUN_FROM_SPIDER = {"»µ Ö© Öë £¡ ", "Öí ÈË ÌÖ Ñá Ö© Öë £¡ ", "ÏÅ ÈË µÄ Ö© Öë "},
    PIG_TALK_HELP_CHOP_WOOD = {"×á Õâ ¿Ã Ê÷ £¡ ", "ÖØ ÖØ »Ø »÷ £¡ ", "Öí ÈË ´ó Á¦ ÇÃ ´ò Õâ ¿Ã Ê÷ £¡"},
    PIG_TALK_ATTEMPT_TRADE = {"Äã µÃ µ½ ÁË Ê² Ã´ £¿ ", "¹Ô ¹Ô Ìý »° "},
    PIG_TALK_PANIC = {"²» £¡ ", "Ì« ºÚ ÁË £¡ Ì« ºÚ ÁË £¡ ", "°¡ £¡ £¡ "},
    PIG_TALK_PANICFIRE = {"ÈÈ ÈÈ ÈÈ £¡ ", "Å¶ £¡ ", "Ëü ÉÕ ×Å ÁË £¡ "},
    PIG_TALK_FIND_MEAT = {"Öí ÈË ¶ö ÁË £¡ ", "Æ¯ ÁÁ £¡ ", "³Ô Ê³ Îï £¡ ", "½ø ²Í Ê± ¼ä £¡"},
    PIG_TALK_EAT_MEAT = {"ßö  ßö  ßö ", "Æ¯ ÁÁ £¡ "},
    PIG_TALK_GO_HOME = {"¸Ã »Ø ¼Ò ÁË £¡ ", "¼Ò £¡ ¼Ò £¡ "},
    PIG_GUARD_TALK_TORCH = {"»ð ¾æ Òª Ï¨ Ãð ÁË ", "µã ÁÁ »ð ¾æ ", "¸ü ÃÍ ÁÒ µØ È¼ ÉÕ "},
    PIG_GUARD_TALK_FIGHT = {"Îª ÁË ¹ú Íõ £¡", "ÊØ ×¡ £¡ ", "Õü ¾È ¹ú Íõ £¡ "},
    PIG_GUARD_TALK_GOHOME = {"Ò» ¶¨ Òª ÊØ ×¡ £¡ ", "Öí ÈË ±£ »¤ ", "¹ú Íõ £¡ ¹ú Íõ £¡ "},
    PIG_GUARD_TALK_LOOKATWILSON = {"Äã ÏÖ ÔÚ ×ß ", "Äã ¿ì ×ß ", "±ð Í£ ÏÂ "},
    

    RABBIT_BATTLECRY = {"Ìø °¡ £¡ ", "É± °¡ £¡ ", "ËÀ °¡ £¡ "},
    RABBIT_MEAT_BATTLECRY = {"ÊÇ Èâ £¡ ", "²» ¸É ¾» £¡ ", "É± ÈË Õß £¡ ", "±¨ ³ð £¡ ", "¹Ö Îï £¡ "},
    RABBIT_GIVEUP = {"Íê ³É ", "Íí Ð© ÔÙ Ëµ "},
    RABBIT_RETREAT = {"¿ì ÅÜ £¡ ", "ÊÜ ÉË ÁË £¡ ", "»Ø ¼Ò £¡ ", "ÅÜ °¡ £¡ "},

    EPITAPHS =
    {
        "Õâ Àï ÌÉ ÏÂ ÁË Ò» Ð© ¼Ò »ï¡£ µÈ µÈ µÈ",
        "Õâ ¿é Ä¹ ±® Ê² Ã´ Ò² Ã» ÓÐ Ð´ ",
        "ÉÏ Ãæ Ëµ £º ¡°Å£ ÄÌ £¬ ¼¦µ° £¬ Ñ¬ Èâ ¡£¡±",
        "ºÙ ÄÇ ÊÇ ÎÒ µÄ Ãû ×Ö £¡",
    },

    TABS =
    {
        TOOLS = "¿ª ²É ¹¤ ¾ß",
        LIGHT = "ÕÕ Ã÷ Éú »ð",
        FARM = "Ê³ Îï À´ Ô´",
        SURVIVAL = "×Ô È» Éú ´æ",
        SCIENCE = "¿Æ Ñ§ ÑÐ ¾¿",
        WAR = "Õ½ ¶· Ðè Çó",
        TOWN = "½¨ Öþ ½¨ Ôì",
        REFINE = "Ìá Á¶ ¾« Á¶",
        DRESS = "·þ ÊÎ ±£ Å¯",
        MAGIC = "Ä§ ·¨ ÑÐ ¾¿",
        BOOKS = "Êé ¼® ÖÆ ×÷",
        GEMOLOGY = "±¦ Ê¯ ¿Æ Ñ§",
        ANCIENT = "Ô¶ ¹Å ¿Æ Ñ§",
    },

    GREENAMULET_TOOLTIP = "¼õ ÉÙ µÄ Ô­ ÁÏ Ïû ºÄ ",
}

STRINGS.BUNNYMANNAMES =
{
    "²¼ À­ Î÷ ¿¨ ",
    "±¾ Äá Ä· ",
    "°Ø ¶à ¿Ë ",
    "ÂÜ ²· ¿Ó ",
    "Èü À³ À­ ¿Ë ",
    "´÷ ¿Ï ",
    "Àï Æ¤ µÂ Ä· ",
    "Âó ¿Ë ÂÞ Î÷ ÑÇ Ë¹ ",
    "ÅÁ Ë¹ Äá ÆÕ ",
    "À­ µÙ Ê² ",
    "Î÷ Ä· ",
    "ÌØ À­ ¸ñ ÆÓ ¸ù ",
    "ÒÁ çê Ä¦ Äá ",
    "Âê Äá »ô ÌØ ",
    "Ã× À­ ±È Àû Ë¹ ",
    "çê Ë÷ À­ Àï ",
    "¿Ï ÄÉ ",
    "Ìá ·¨ ",
    "½ð ¼ª ²® ",
    "°Â ¿Ë Èø Àï Ë¹ ",
    "Ë÷ À­ Åµ Ä· ",
    "ÎÚ ¶û Â¬ ¿Ë Ë¹ ",
    "¿â çê Â³ Ë¹ ",
    "°¢ Æ¤ ¶ò Ë¹ ",
    "É½ Ò© ¾Õ ",
    "°Â ¶û ÌØ ÁÖ ²é Ä· ",
    "°Í ÎÄ ",
    "²¨ À³ ÂÞ ",
    "²ý ÌØ ÄÚ ",
    "Ô¶ Õ÷ Õß ",
    "µ¤ ¸¥ Ë¹ ",
    "¶Å Éª ",
    "¸¥ À­ »ù ",
    "¸Ç ÀÊ µÂ ",
    "Ï£ ÅÁ ¿Ë",
    "µÛ Íõ ",
    "Öì Íß Âå ÌØ ",
    "¿¨ Âå Ì¹ ",
    "Âí ¸ñ Åµ ",
    "ÄÏ ÌØ Ë¹ ",
    "Äá ¶û É­ ",
    "°º ÎÖ µÂ ",
    "Å£ ÐÄ ",
    "ÅË Åå ÄÚ ¶û ",
    "À³ µÂ Ï£ ¶û µÂ ",
    "À³ µÂ À¼ µÂ ",
    "ËÕ ¿â ",
    "Ä´ Ö¸ ¹Ã Äï ",
    "´ó ÅÖ ×Ó ",
    "Ëþ ²ý ",
    "ÎÚ ²ý ",
    "Î¬ À­ Àû ",
    "Ð¡ »Æ ",
    "¼¾ Åµ ",
    "Ë¹ ¿² µÏ Ë¹ ",
    "ÒÁ ÌØ Àï ÑÇ ",
    "À¼ É£ ",
    "Èü ÁÐ Ä· ",
    "ÆÕ ÀÙ Ë÷ µÒ Ã× ÑÇ ",
    "Äá Å· µÒ Ã× ÑÇ ",
    "ÆÕ Âå Ä· Î÷ ÑÇ ",
    "Èø Âê Àû ",
    "ÓÈ ÂÞ Æ¤ ÑÇ ",
    "¼Ó ¶à ÁÖ ",
    "ÌØ ±È ÑÇ ",
    "µÏ Ë¹ ÆÕ Âå Ë¹ ",
    "»ô ¶û Ã× ÑÇ ",
    "¶ò ±È Ò® Ä· ",
    "Í¼ Àï Ò® Ä· ",
    "ÒÁ ÌØ ±È ÑÇ ",
    "Â³ ÌØ Ìá Ò® Ä· ",
}

STRINGS.PIGNAMES=
{
    --emperors
    "°Â ¹Å Ë¹ ¶¼ ",
    "Ìá ±Ê ÂÔ ",
    "¿¨ Àï ¹Å À­ ",
    "¿Ë ÀÍ µÏ ÑÇ Ë¹",
    "Äá Â»",
    "¸Ç ¶û °Í ",
    "°Â Ë÷",
    "Î¬ ÌØ Àï ÎÚ Ë¹ ",
    "Î¬ Ë¹ ÅÁ ÏÈ",
    "Ìá Í¼ Ë¹",
    "Í¼ ÃÜ ÉÆ ",
    "Äù ¶û Íß ",
    "Í¼ À­ Õæ ",
    "¹þ µÂ Á¼ ",
    "°² ¶« Äá ¶í Ë¹ ",
    "Â¬ ÐÞ Ë¹ ",
    "Âí ¿â Ë¹ ",
    "¿µ Ã¯ µÂ ",
    "Åå µÙ ÄÉ ¿Ë Ë¹ ",
    "µÏ µÏ ÎÚ Ë¹ ",
    "Èü ÆÕ µÏ Äª Ë¹ ",
    "¿¨ À­ ¿¨ À­ ",
    "¸Ç ÌØ ",
    "Âí ¿Ë ÁÖ Å¬ Ë¹ ",
    "°£ À­ Ù¤ °Í Â· Ë¹ ",
    "Î÷ ¸¥ ÀÕ Ë¹ ",
    "Âí ¿Ë Î÷ Ä· ",
    "¸ê ¶û µÏ ",
    "ÆÕ ±È Å¦ Ë¹ ",
    "°Í ¶û ±È Å¬ Ë¹ ",
    "·Æ Àû ÆÕ ",
    "»ô Ë¹ µÒ Àï °² ",
    "ÌØ ²® Àï °² Å¬ Ë¹ ",
    "°£ Ã× Àû °² Å¬ Ë¹ ",
    "Íß ÀÕ Á¼ ",
    "¼Ó Àï ¶÷ Å¬ Ë¹ ",
    "À¥ Ìá Â¬ Ë¹ ",
    "°Â ÀÕ Á¼ ",
    "Ëþ Î÷ Ù¢ ",
    "·ð Âå Àï °² ",
    "ÆÕ ÂÞ ²¼ Ë¹ ",
    "¿¨ Â³ Ë¹ ",
    "Å¬ Ã· Àï °² ",
    "¿¨ Àï Å¬ Ë¹ ",
    "´÷ ¿Ë Àï ÏÈ ",
    "Âí ¿Ë Î÷ Ã× °² ",
    "¾ý Ê¿ Ì¹ Ìá Ë¹",
    "¼Ó À³ Àï ÎÚ Ë¹ ",
    "¿µ Ë¹ Ì¹ ¶¡ ",
    "Âí ¿Ë É­ Ìá ÎÚ Ë¹ ",
    "Àî Îý Äá ",
    "¿µ Ë¹ Ì¹ Ë¹ ",
    "Î¬ ÌØ À­ Åµ ",
    "Öì Àû °² ",
    "Ô¼ Î¬ °²",
    "Íß Â× Ìá Äá °² ",
    "Íß Â× Ë¹ ",
    "¸ñ À­ Ìá °² ",
    "µÒ °Â ¶à Î÷ ",
    "°¢ ¿¨ µÏ °Â Ë¹ ",
    "ºÉ Åµ Àï ",
    "Öì Àû °² Ë¹ ",
    "Âí ¶û Ææ °² ",
    "Åå ÌØ Âå Äá ÎÚ Ë¹ ",
    "°¢ Î¬ Í¼ Ë¹ ",
    "Âí Ô¼ ÁÖ ",
    "Àû ²¼ Ê² ",
    "°² ÌØ Ã× ÎÚ Ë¹ ",
    "°Â Àû ²¼ Àï ÎÚ Ë¹ ",
    "¸ñ Àï Ï£ Àï ÎÚ Ë¹",
    "Öì Àû Ò¶ Ë¹ ",
    "ÂÞ Ä½ Â· Ë¹ ",
    "Àï °Â ",
    "Æë Åµ ",
    "°Í Ë¹ Àû ¿Ë Ë¹ ",
    "°² Ëþ ËÕ Ë¹ ",
    "¼Ö Ë¹ Í¡ ",
    "²é Ê¿ ¶¡ Äá ",
    "Äª Àï Ë¹ ",

    --forum fun
    "Ã× Ææ",

    --dev team
    "¿­ ÎÄ ",
    "Öì Àò °² ",
    "°¬ Àò ÑÇ",
    "Ì© Éª Ä· ",
    "²¼ Â³ ¿Ë ",
    "Âí ÌØ",
    "°¬ Àû ¿Ë Ë¹ ",
    "¿­ Àû ",
    "ÓÈ ½ð ",
    "¸ñ À× ºº Ä· ",
    "½Ü Ã× ",
    "½Ü ·ò ",
    "ÇÇ ",
    "¿Æ Àï ",
    "²¼ À³ Ë¹ ",
    "°Í ¸ñ", --Joe's kid
    "Èü Ë¹",

    --food that Sloth likes
    "Ð¡ Ìð ±ý",
    "°Ù ¼ª ±ý ",
    "±ý ¸É ",
    "Åà ¸ù ",
    "ºº ÃÜ ¶û ¶Ù ",
    "¹þ Ä· ",
    "P ÏÈ Éú ",
    "ÇÉ ¿Ë Á¦ µ° ¸â ",
    "»Æ ÓÍ ",
    "½ð Ç¹ Óã",
    "ÜÙ Þ£ ",
    "Ò¬ ×Ó Ê÷ ",
    "ÄÌ ÓÍ ¶³ ",
    "½È ×Ó ",
    "µ° µ° ",
    "â¨ ºï ÌÒ ",
    "·¨ À¼ ¿Ë ¸£ Ïã ³¦ ",
    "»ª ·ò ±ý ¸É",
    "ÄÌ ÓÍ ¼Ð ÐÄ ±ý ",
    "ËÉ Â¶ ÇÉ ¿Ë Á¦ ÌÇ ",
    "Âí Áå Êí ",
    "ÇÐ ´ï ÄÌ ÀÒ ",
    "ÄÏ ¹Ï ",
    "Å· µØ",
    "Å· Äá ¿Ë ",
    "Óñ Ã× Æ¬ ",
    "ÉÆ Öª Äñ ",
    "Ìð Ìð È¦ ",
    "¾í ÐÄ ²Ë ",
    "²¨ Ææ ",
    "²© ½ð Ë¹ ",
    "²® ¿Ë ±¾ ",
    "À± ½· ",
    "¸ß µÂ ¸É ÀÒ ",
    "°£ ¿Ë ±´ ¶û ÌØ ",
    "Ëé Æ¬ ",
    "½¬ ¹û ",
    "¿Ë À³ ±È ",
    "Â³ ±ö ",
    "´ó Âó ",
    "éÏ é­ ",
    "ëç ²Ë ",
    "ÄÌ ÓÍ É³ Ë¾ Çà ¶¹ ÉÕ Óã ",
    "Å£ Èâ ¸É ",
    "ÄÑ ÎÅ µÄ ",
    "ÏÌ µÄ ",
}

STRINGS.UI =
{
    HELP =
    {
        SCROLLBACK ="ÉÏ Ò» Ò³",
        SCROLLFWD = "ÏÂ Ò» Ò³",
        PREVVALUE = "ÏÈ Ç° µÄ Öµ",
        NEXTVALUE = "ÏÂ Ò» ¸ö Öµ",
        REVERT = "»¹ Ô­ ¸ü ¸Ä",
        ACCEPT = "Íê ³É ¸ü ¸Ä",
        APPLY = "Ó¦ ÓÃ ¸ü ¸Ä",
        SELECT = "Ñ¡ Ôñ",
        BACK = "·µ »Ø",
        NEXTCHARACTER = "ÓÒ",
        PREVCHARACTER = "×ó",
        ROTATE_LEFT = "Ïò ×ó Ðý ×ª ",
        ROTATE_RIGHT = "Ïò ÓÒ Ðý ×ª ",
        ZOOM_IN = "·Å ´ó",
        ZOOM_OUT = "Ëõ Ð¡",

    },
    CHARACTERSELECT=
    {
        SELECT = "Ñ¡ Ôñ",
        APPLY = "Ó¦ ÓÃ",
        CANCEL = "È¡ Ïû",
    },
    
    CRAFTING=
    {   
        PLACE = "°² ÖÃ ",
        BUILD = "½¨ Ôì ",
        PROTOTYPE = "ÑÐ ·¢ Ô­ ÐÍ",
        NEEDSTUFF = "ÕÒ µ½ Ô­ ÁÏ À´ ÖÆ ×÷ £¡ ",
        BUILD = "ÖÆ ×ö ",
        RESEARCH = "ÑÐ ¾¿ ",
        NEEDSCIENCEMACHINE = "Ðè Òª ÓÃ ¿Æ Ñ§ »ú Æ÷ ÑÐ ·¢ Ò» ¸ö Ô­ ÐÍ Ìå £¡ ",
        NEEDALCHEMYENGINE = "Ðè Òª ÓÃ Á¶ ½ð Òý Çæ ÑÐ ·¢ Ò» ¸ö Ô­ ÐÍ Ìå £¡",
        NEEDSHADOWMANIPULATOR = "Ðè Òª ÓÃ °µ Ó° ²Ù ×Ý Æ÷ ÑÐ ·¢ Ò» ¸ö Ô­ ÐÍ Ìå £¡ ",
        NEEDPRESTIHATITATOR = "Ðè Òª ÓÃ Ä§ ·¨ Ã± ×Ó ÑÐ ·¢ Ò» ¸ö Ô­ ÐÍ Ìå £¡ ",
        NEEDSANCIENT_FOUR = "¿´ Æð À´ Õâ ¸ö Ê¥ Ì³ ¹¦ ÄÜ »¹ ²» Íê È« £¡ ",
        CANTRESEARCH = "ÓÐ Ð© ¶« Î÷ ÈÔ È» Î´ Öª ",
    },
    
    DEATHSCREEN=
    {
        MAINMENU = "Ö÷ ²Ë µ¥ ",
        RETRY = "ÖØ ÊÔ ",
        CONTINUE = "¼Ì Ðø ",
        YOUAREDEAD = "Äã ËÀ ÁË £¡ ",
        YOUESCAPED = "Äã ÌÓ ÍÑ ÁË £¡ ",
        DAYS = "Ìì ",
        DAY = "Ìì Êý \n",
        SURVIVEDDAYS = "Äã »î ÏÂ À´ ÁË ",
        NEXTREWARD = "ÏÂ Ò» ¸ö ½± Àø ¡­¡­",
        LEVEL = "µÈ ¼¶  ",
        ATCAP = "ÔÚ Ã± ×Ó Àï £¡ ",
    },
    
    CREDITS=
    {
        TITLE = "ÖÆ×÷×é",
        NAMES=
        {
            "Kevin Forbes",
            "Ju-Lian Kwan",
            "Alia McCutcheon",
            "Alia McCutcheon",
            "Tatham Johnson",
            "Graham Jans",
            "Brook Miles",
            "Bryce Doig",
            "Charles Bostik",
            "Wade Lindley",
            "Joe Wreggelsworth",
            "Corey Rollins",
            "Matthew Marteinsson",
            "Jason Garner",
            "Vince de Vera",
            "Jeff Agala",
            "Alex Savin",
            "Sloth Trakhtenberg",
            "Kelly Graham",
            "Allan Cortez",
            "Aaron Bouthillier",
            "David Forsey",
            "Kaj Eijlers",
            "Jan Hutchings",
            "Seth Rosen",
            "Johann Seidenz",
            "Paul Ku",
        },--Î´·­Òë

        ALTGAMES = 
        {
            TITLE = "Linux and OSX ports by Alternative Games",
            NAMES = 
            {
                "Turo Lamminen",
                "Tuomas Narvainen", 
                "Tapio Honkonen",
            },
        },--Î´·­Òë

        THANKYOU = "Thank you!",
        EXTRA_THANKS = "Ophir Lupu\nKo Kim\nColt McAnlis",
        EXTRA_THANKS_2 = "Pieter Wycoff\nMatthew Nickerson\nAnna Sweet",
        SONY_THANKS = "Shane Bettenhausen\nAdam Boyes\nBrian Silva\nNick Suttner",
        
        BABEL =
        {
            TITLE = "Babel",
            NAMES1 =
            {
                "Guillaume Langlois",
                "Danny Labrie",
                "Dominic Knowles",          
                "Marc Kent",
                "Jeff LeGresley",
            },
            NAMES2=
            {
                "Jon Morrell",
                "JP Bergevin",
                "Mike Holdaway",
                "Jonas Miller",
                "Katri Luotonen",
            }           
        },
        THANKS = "And a very special thanks to all our supporters who braved the challenge of the \"Early-Access Beta\".\nYou are too numerous to name - our amazing moderators, the wonderful artists, musicians, live streamers,\nto all who made a Let's Play video and everybody who chimed in to let us know exactly what you think.\nYour encouragement, passion and support has been amazing.\n\nDon't Starve is truly a better game because of all of you.",

        FMOD = "FMOD Sound System,\nCopyright Firelight Technologies",

        FACEBOOK = "The Facebooks",
        TWITTER = "The Twitters",
    },--Î´·­Òë
    
    WORLDGEN=
    {
        TITLE = "ÊÀ ½ç Éú ³É ÖÐ ",
        CAVETITLE = "´´ Ôì ¶´ Ñ¨ ",
        VERBS = 
        {
            "Õù ³³ ",
            "²ú Éú ",
            "Ðó ÄÁ ",
            "Ô­ ÐÍ",
            "Ñ­ »· ·Ã ÎÊ ",
            "°µ Ê¾ ",
            "Íø ×´ »¯ ",
            "²å Èë ",
            "¹¹ Ôì ",
        },
        NOUNS=
        {
            "Ê÷ Ä¾ ",
            "±¯ âê ",
            "ËÉ Ê÷ ",
            "Ö© Öë ",
            "¹Ö Îï ",
            "³Á ÖØ µÄ ¾ø Íû ¸Ð ",
            "Íþ ¶û Ñ· µÄ ºú Ðë ",
            "³É Í° ³É Í° µÄ Õ½ Àû Æ· ",
            "ÓÎ Ï· Ô­ Àí ",
            "Ê³ Îï ",     
        }
    },
    EMAILSCREEN=
    {
        SIGNUPSUBMITTITLE="·¢ ËÍ ¡­¡­",
        SIGNUPSUBMIT="Çë µÈ ´ý ÎÒ ÃÇ ¸ø Äã ×¢ ²á ",
        SIGNUPSUCCESSTITLE="³É ¹¦ £¡ ",
        SIGNUPSUCCESS="¸Ð Ð» ×¢ ²á £¡ Äã Ó¦ ¸Ã ÒÑ ÊÕ µ½ Ò» ·â È· ÈÏ ÓÊ ¼þ ",
        SIGNUPFAILTITLE="Ê² Ã´ ¶« Î÷ ³ö ´í ÁË ",
        SIGNUPFAIL="ÎÒ ÃÇ ×¢ ²á Äã Ê± ËÆ ºõ Óö µ½ ÁË Âé ·³ ¡£Èç ¹û Äã Ã» ÓÐ ÊÕ µ½ Ò» ¸ö È· ÈÏ ÓÊ ¼þ Çë ÉÔ ºó ÔÙ ÊÔ Ò» ´Î ",
        INVALIDEMAILTITLE= "ÎÞ Ð§ µÄ µç ÓÊ µØ Ö· ", 
        INVALIDEMAIL= "ÎÒ ÃÇ ²» ÊÇ Î× Ê¦ £¡ Èç ¹û Äã ²» Êä Èë Äã µÄ µç ×Ó ÓÊ Ïä µØ Ö· £¬ ÎÒ ÃÇ ÎÞ ·¨ Í¨ Öª Äã ÐÂ µÄ ÓÎ Ï· ÄÚ ÈÝ ",
        INVALIDDATETITLE= "ÎÞ Ð§ ÈÕ ÆÚ ", 
        INVALIDDATE= "ÎÒ ÃÇ Ðè Òª Äã µÄ Éú ÈÕ ·ñ Ôò ÆÀ ¼¶ µÄ ÈË ÃÇ ¿É ÄÜ »á Òò Îª ÎÒ ÃÇ ¸ø Äã ·¢ ²» ÊÊ ºÏ Äã Äê Áä µÄ µç ×Ó ÓÊ ¼þ ¶ø Éú Æø ",
        OK = "È· ¶¨ ",
        SUBSCRIBE = "¶© ÔÄ ",
        CANCEL = "È¡ Ïû ",
        TITLE = "Ëæ Ê± ¸ü ÐÂ ¡¶¼¢ »Ä ¡·ÐÂ ÎÅ ",
        EMAIL = "µç ÓÊ µØ Ö· £º",
        BIRTHDAY = "Éú ÈÕ £º ",
        BIRTHDAYREASON = "ÎÒ ÃÇ Ðè Òª Öª µÀ Äã µÄ Éú ÈÕ £¬ ÒÔ ±ã ·¢ ËÍ ºÏ ÊÊ µÄ Éý ¼¶ ²¹ ¶¡ ¸ø Äã £¡ \r\n±ð µ£ ÐÄ £¬ ÎÒ ÃÇ ²» »á Ð¹ Â¶ »ò ³ö ÊÛ Äã µÄ ¸ö ÈË ÐÅ Ï¢ ",
        JAN="Ò» ÔÂ ",
        FEB="¶þ ÔÂ ",
        MAR="Èý ÔÂ ",
        APR="ËÄ ÔÂ ",
        MAY="Îå ÔÂ",
        JUN="Áù ÔÂ",
        JUL="Æß ÔÂ",
        AUG="°Ë ÔÂ",
        SEP="¾Å ÔÂ",
        OCT="Ê® ÔÂ",
        NOV="Ê® Ò» ÔÂ",
        DEC="Ê® ¶þ ÔÂ",
        MONTH = "ÔÂ",
        DAY = "Ìì",
        YEAR = "Äê",
    },
    
    MAINSCREEN =
    {
        NOTIFY = "×Ê Ñ¶ ¼ò ±¨ ",
        FORUM = "ÂÛ Ì³ ",
        BUYNOW = "ÏÖ ÔÚ ¹º Âò",
        GIFT = "Ôù ËÍ Àñ Îï ",
        MODTITLE = "Mod ÒÑ °² ×° £¡",
        MODDETAIL = "ÒÑ °² ×° µÄ mod £º",
        NEWMODDETAIL = "ÐÂ °² ×° µÄ mod £º ",
        NEWMODDETAIL2 = "ÔÚ Ö÷ ²Ë µ¥ ÉÏ Æô ÓÃ Õâ Ð© mod ",
        MODDETAIL2 = "Ê¹ ÓÃ mod Ê± ¿É ÄÜ »á ³ö ÏÖ ÎÊ Ìâ ¡£Çë ½÷ É÷ Ê¹ ÓÃ £¡",
        FORCEMODDETAIL = "ÒÔ ÏÂ mod ÒÑ ±» Ç¿ ÖÆ ÔØ Èë £¬ ½« Ê¼ ÖÕ ´¦ ÓÚ Æô ÓÃ ×´ Ì¬ £º ",
        OLDMODS = "ÏÂ Ãæ µÄ mod ¹ý ÆÚ ÁË £¬ ÒÑ ¾­ ±» ½û ÓÃ £º",
        FAILEDMODS = "ÉÏ ´Î Ê¹ ÓÃ ÒÔÏÂ mod Ê± ³ö ´í £¬ ÒÑ ½û ÓÃ £º ",
        OLDORFAILEDMODS = "¼ì ²é ÂÛ Ì³ ÊÇ ·ñ ÓÐ ¸ü ÐÂ µÄ °æ ±¾ ",
        MODFAILTITLE = "¾¯ ¸æ £¡ ",
        MODFAILDETAIL = "ÏÂ ÁÐ mod Òý ·¢ ÁË ¹Ê ÕÏ £º",
        MODFAILDETAIL2 = "´Ë mod ½« ±» ½û ÓÃ £¬ ¿É ÔÚ mod ²Ë µ¥ ÉÏ ÖØ ÐÂ Æô ÓÃ ",
        MODQUIT = "½û ÓÃ mod ",
        MODFORUMS = "Mod ÂÛ Ì³ ",
        MODSBADTITLE = "Ëù ÓÐ µÄ mod ¶¼ ±» ½û ÓÃ ÁË ",
        MODSBADLOAD = "Ä³ ¸ö mod ³ö ´í µ¼ ÖÂ ÎÞ ·¨ Õý ³£ Æô ¶¯ ÓÎ Ï· ¡£ÒÑ ½û ÓÃ Ëù ÓÐ µÄ mod ¡£\n\nÄã ¿É ÒÔ ÔÚ mod Éè ÖÃ ÖÐ ³¢ ÊÔ ½« Æä ÖØ Æô ",
        MODS = "Mods",
        SCRIPTERRORQUIT = "ÍË ³ö ÓÎ Ï· ",
        SCRIPTERRORMODWARNING = "¿É ÄÜ ÊÇ Äã Æô ÓÃ µÄ Ò» ¸ö mod µ¼ ÖÂ ÁË Õâ ¸ö ´í Îó £¡ \nÏÂ ÁÐ mod ÒÑ ±» Æô ÓÃ £º \n",
        TESTING = "Õâ ÊÇ ²â ÊÔ ·Ö Ö§ ", 
        TESTINGDETAIL = "ÔÚ ÎÒ ÃÇ Éý ¼¶ ÓÎ Ï· Ê± £¬ Äã ¿É ÄÜ Ôâ Óö ´í Îó »ò Õß ÓÎ Ï· Ëð »µ £¬ Ò² ¿É ÄÜ ¶ª Ê§ ±£ ´æ µÄ ÓÎ Ï· ÄÚ ÈÝ ¡£Çë ÔÚ ÂÛ Ì³ ÉÏ ±¨ ¸æ Ëù ÓÐ ÎÊ Ìâ ",
        TESTINGNO = "²» £¬ Ð» Ð» £¡ ",
        TESTINGYES = "ÎÒ Öª µÀ ÁË ",
        CONTINUE = "¼Ì Ðø ",
        DELETE = "É¾ ³ý ",
        RESTART = "ÖØ ÐÂ ¿ª Ê¼ ",
        NEWADVENTURE_WARN = "ÐÂ µÄ Ã° ÏÕ ÄÚ ÈÝ µ± Ç° ¿É ÓÃ £¬ µ« ×÷ Îª ²â ÊÔ °æ ±¾ £¬ Æä ÖÐ ¿É ÄÜ °ü º¬ Ä³ Ð© Â© ¶´ ",
        NEWADVENTURE = "Ã° ÏÕ £¨ ²â ÊÔ £© ",
        NEWFREEPLAY = "É³ ºÐ Ä£ Ê½",
        NEWFREEPLAYCUSTOM = "É³ ºÐ Ä£ Ê½ £¨ ¶¨ ÖÆ £© ",
        NEWGAMESHORT = "ÎÞ ÄÚ ÈÝ ",
        UNKNOWNGAME = "Î´ Öª ",
        NEWGAMETYPE = "Äã Ï² »¶ Ê² Ã´ Àà ÐÍ µÄ ÓÎ Ï· £¿ ",
        SLOTACTION = "Äã Ïë Òª µã Ê² Ã´ £¿ ",
        ADVENTURE = "Ã° ÏÕ ",
        FREEPLAY = "É³ ºÐ Ä£ Ê½ ",
        SLOT = "ÓÎ Ï· Î» ÖÃ ",
        SLOT_1 = "1",
        SLOT_2 = "2",
        SLOT_3 = "3",
        SLOT_4 = "4",
        IMPORT = "Êä Èë ",
        CANCEL = "È¡ Ïû ",
        SETTINGS = "Éè ÖÃ ",
        OPTIONS = "Ñ¡ Ïî ",
        PLAYDEMO = "¿ª Ê¼ ÊÔ Íæ °æ ",
        ENTERPRODUCTKEY = "Êä Èë ÃÜ Âë ",
        ENTERKEY = "Êä Èë ÐÂ ÃÜ ³× ",
        RESETPROFILE = "ÖØ ÖÃ µµ °¸ £¡ ",
        UNLOCKEVERYTHING = "½â Ëø Ò» ÇÐ ",
        SURE = "Äã È· ¶¨ Âð £¿",
        YES = "ÊÇ",
        NO = "·ñ ",
        CHEATS = "×÷ ±× Âë ",
        PLAY = "¿ª Ê¼ ÓÎ Ï·",
        RATE = "¸ø ¸Ã ÓÎ Ï· ´ò ·Ö ",
        ACCOUNTINFO = "ÕË »§ ÐÅ Ï¢ ",
        VISITFORUM = "·Ã ÎÊ ÂÛ Ì³ ",
        MOREGAMES = "¸ü ¶à ÓÎ Ï· ",
        CHOOSEDIR = "¡¶¼¢ »Ä ¡·ÓÎ Ï· Êý ¾Ý ",
        IMPORTSUCCESS = "³É ¹¦ ",
        IMPORTSUCCESSDESC = "³É ¹¦ Êä Èë Êý ¾Ý ",
        OK = "È· ¶¨ ",
        IMPORTFAIL = "¶Á È¡ Ê§ °Ü ",
        GREETING = "àË  ",
        NEWWORLD = "´´ ½¨ ÐÂ ÊÀ ½ç £¡ ",
        NEWWORLDDESC = "Õâ »á É¾ ³ý Äã µ± Ç° µÄ ÊÀ ½ç ºÍ ±£ ´æ ÔÚ Æä ÖÐ µÄ ÓÎ Ï· ÄÚ ÈÝ ¡£ÊÇ ·ñ ¼Ì Ðø £¿ ",
        RESETGAMEDESC = "Õâ »á ÖØ ÖÃ Äã µ± Ç° µÄ ÊÀ ½ç ¡£ÊÇ ·ñ ¼Ì Ðø £¿",
        NEWGAMEDESC = "Õâ »á É¾ ³ý Äã µ± Ç° µÄ ´æ µµ ¡£ÊÇ ·ñ ¼Ì Ðø £¿ ",
        ADVGAMEDESC = "×¢ Òâ £º ¸Ã ÓÎ Ï· Ä£ Ê½ ÉÐ ÔÚ ¿ª ·¢ ÖÐ ¡£\n\nÖ» ¶Ô ÓÐ ¾­ Ñé µÄ Íæ ¼Ò ¿ª ·Å £¡ \n\nÄã ÒÑ ¾ö ¶¨ Òª ºÍ Âó Ë¹ Íþ ¶û Õ½ ¶· ¡£\nÄã ÄÜ ÔÚ Ëû Îª Äã ´´ Ôì µÄ ¿Á ¿Ì Ìõ ¼þ ÏÂ ´æ »î ÏÂ À´ £¬ ²¢ ÔÚ Ëû µÄ ÓÎ Ï· ÖÐ ´ò °Ü Ëû Âð £¿ ",
        NEWGAME = "¿ª Ê¼ ÐÂ ÓÎ Ï· £¡",
        NEWGO = "¿ª Ê¼ £¡",
        ASKQUIT = "Äã Õæ µÄ Òª ÍË ³ö Âð £¿",
        ASKQUITDESC = "Âó Ë¹ Íþ ¶û »á Ïë Äã µÄ £¡",

        FRESHBUILD = "ÐÂ ½¨ £¡ ",
        LASTBUILDDAYS = "ÉÏ Ò» ´Î ¸ü ÐÂ ÔÚ %d Ìì Ç°",
        NEXTBUILDIMMINENT = "ÏÂ Ò» ´Î ¸ü ÐÂ ¼´ ½« µ½ À´ £¡ ",
        NEXTUPDATEDAYS = "ÏÂ ´Î Éý ¼¶ £º %d Ìì ºó ",
        
        MOTDTITLE = "Mod ÖÆ ×÷ Ìô Õ½ Èü ",
        
        MOTD = "µã »÷ ÏÂ ·½ µÄ Á´ ½Ó £¬ ²Î ¼Ó ÎÒ ÃÇ µÄ Íò Ê¥ ½Ú Mod ÖÆ ×÷ Ìô Õ½ Èü £¡",
        MOTDBUTTON = "¼Ó Èë ÎÒ ÃÇ ",
        EXIT = "ÍË ³ö ",
        LOGOUT = "×¢ Ïú ",
        CREDITS = "ÖÆ ×÷ ×é ",
        UPDATENAME = "Âó Ë¹ Íþ ¶û £¬Ò» ÇÐ ¶¼ ºÃ ",
        DLC_UPDATENAME = "¾Þ ÈË µÄ ²½ ·¥",
        CONTROLS = "¿Ø ÖÆ ",

        PLAY_ON_STEAM = "ÔÚ STEAM Æ½ Ì¨ ÉÏ ½ø ÐÐ ÓÎ Ï· ",
        PLAY_ON_STEAM_DETAIL = "¿É ÒÔ Ê¹ ÓÃ ¸ü ¶à ¸ü ºÃ µÄ Mod £¡",
        LATER = "²» ÊÇ ÏÖ ÔÚ ",
        ADJUST_DISPLAY_HEADER = "µ÷ Õû ÏÔ Ê¾ Çø Óò ",
        ADJUST_DISPLAY_TEXT = "ÓÎ Ï· »­ Ãæ ¿É ÄÜ »á ³¬ ³ö ÆÁ Ä» ¡£ \n Äã Ïë Òª Á¢ ¼´ ¼ì ²é ²¢ µ÷ Õû ÓÎ Ï· »­ Ãæ ÒÔ ÊÊ Ó¦ Äã µÄ ÏÔ Ê¾ Çø Óò Âð £¿ \n Äã ¿É ÒÔ ÉÔ ºó ÔÚ Éè ÖÃ ²Ë µ¥ ÖÐ ½ø ÐÐ µ÷ Õû ",

        SCREECHER_DIALOG_TITLE = "Ðè Òª ÖØ Æô ",
        SCREECHER_DIALOG_TEXT = "Ðè Òª ÖØ Æô ÓÎ Ï· ²Å ÄÜ Æô ÓÃ ¡¶ ¼â Ð¥ ¡· Mod",
        SCREECHER_NACL_DIALOG_TITLE = "¡¶ ¼â Ð¥ ¡· Õý ÔÚ µÈ ×Å Äã¡­¡­",
        SCREECHER_NACL_DIALOG_TEXT = " ¡¶ ¼â Ð¥ ¡· Ðè Òª ÔÚ Steam »ò ¡¶ ¼¢ »Ä ¡· µ¥ »ú °æ ÖÐ ÔË ÐÐ",
        SCREECHER_NACL_OKAY = "ÁË ½â ¸ü ¶à",

        CANT_LOAD_TITLE = "ÔØ Èë Ê§ °Ü",
        CANT_LOAD_ROG = "Î´ °² ×° ¡¶ ¾Þ ÈË µÄ Í³ ÖÎ ¡· ¡£ ÎÞ ·¨ ¼Ó ÔØ",

        CONSOLE_EDITION_TEXT = "¿ØÖÆÌ¨"
    },
    
    HUD =
    {
        MAP = "ÏÔ Ê¾ µØ Í¼ \n(TAB)",
        BUYNOW = "ÏÖ ÔÚ ¹º Âò ",
        READYTITLE = "×¼ ±¸ ÓÎ Ï· £¡",
        READY = "Äã »á ´æ »î ¶à ¾Ã ÄØ £¿ ",
        START = "¿ª Ê¼ ",
        CLOCKDAY = "Ìì Êý \n",
        SAVING = "±£ ´æ ÖÐ ¡­¡­",
        WORLD = "ÊÀ ½ç \n",
        BUILD = "½¨ Ôì",
        HERE = "Õâ Àï",
        STALE = "³Â ¾É µÄ ",
        STALE_FROZEN = "ÈÚ »¯",
        SPOILED = "±ä ÖÊ µÄ ",
        SPOILED_FROZEN = "ÈÚ »¯ µÄ",
        ROTLEFT = "Äæ Ê± Õë Ðý ×ª \n (Q)",
        ROTRIGHT = "Ë³ Ê± Õë Ðý ×ª \n (E)",
        PAUSE = "ÔÝ Í£ \n (ESC)",
        INSPECT = "¼ì ²é ",
        TAKE = "ÄÃ ×ß ",
        DROP = "¶ª µô ",
        SWAP = "½» »» ",
        EQUIP = "×° ±¸ ",
        UNEQUIP = "Ð¶ ÏÂ ",
        PUTONE = "·Å ÏÂ Ò» ¸ö ",
        GETHALF = "ÄÃ ×ß Ò» °ë ",
        SELECT = "Ñ¡ Ôñ ",
        PUT = "·Å ÏÂ ",
        DEPLOY = "°² ÖÃ ",
        BUILD = "½¨ Ôì",
        CANCEL = "È¡ Ïû ",
        ATTACK = "¹¥ »÷ ",
        WHACK = "ÖØ »÷",
        HUNGRY = "¼¢ ¶ö",
        STARVING = "¿ì ¶ö ËÀ",
    },
    
    OPTIONS=
    {
        YES = "ÊÇ",
        NO = "·ñ",
        BACKTITLE = "»Ø µ½ ÓÎ Ï· £¿",
        BACKBODY = "Äã Ïë Òª ·Å Æú Õâ Ð© ¸ü ¸Ä Âð £¿",
        ACCEPTTITLE = "È· ÈÏ ¸ü ¸Ä ",
        ACCEPTBODY = "Äã È· ÈÏ ½Ó ÊÜ Õâ Ð© Éè ÖÃ ¸ü ¸Ä Âð £¿",
        ACCEPTGRAPHICSTITLE = "È· ÈÏ ¸ü ¸Ä ",
        ACCEPTGRAPHICSBODY = "Äã È· ÈÏ ½Ó ÊÜ Õâ Ð© Éè ÖÃ ¸ü ¸Ä Âð £¿ ",
        ACCEPT = "½Ó ÊÜ",
        CANCEL = "È¡ Ïû",
        REVERT = "»Ø µ½ ÓÎ Ï· ",
        APPLY = "Ó¦ ÓÃ",
        CLOSE = "¹Ø ±Õ",
        BLOOM = "Bloom äÖ È¾",
        DISTORTION = "Ê§ Õæ ÌØ Ð§",
        FULLSCREEN = "È« ÆÁ ",
        DISPLAY = "ÏÔ Ê¾ ",
        RESOLUTION = "·Ö ±æ ÂÊ ",
        REFRESHRATE = "Ë¢ ÐÂ ÂÊ ",
        SMALLTEXTURES = "½Ï Ð¡ ÎÆ Àí ",
        NETBOOKMODE = "ÉÏ Íø ±¾ Ä£ Ê½",
        ENABLED = "Æô ÓÃ",
        DISABLED = "¹Ø ±Õ",
        FX = "Òô Ð§ ",
        MUSIC = "Òô ÀÖ ",
        AMBIENT = "»· ¾³ Òô Ð§ ",
        HUDSIZE = "Í¼ ±ê ´ó Ð¡ ",
        VIBRATION = "Õð ¶¯ ",
        DISPLAY_AREA_LABEL = "ÏÔ Ê¾ Çø Óò ",
        DISPLAY_AREA_BUTTON = "µ÷ Õû ",
        -- INPUTFREQENCY = "Input Frequency(hz):",
        AUTOSAVE = "×Ô ¶¯ ±£ ´æ",
    },
    
    PAUSEMENU =
    {
        TITLE = "ÔÝ Í£ ",
        SAVEANDQUITTITLE = "±£ ´æ ²¢ ·µ »Ø Ö÷ ²Ë µ¥ £¿ ",
        SAVEANDQUITBODY = "±ð µ£ ÐÄ ¡ª¡ª ÎÒ ÃÇ µÈ ×Å Äã",
        SAVEANDQUITYES = "ÎÒ Ëµ ÍË ³ö !",
        SAVEANDQUITNO = "Ëã ÁË ¡­¡­",
        QUITTITLE = "·µ »Ø Ö÷ ²Ë µ¥ £¿ ",
        QUITBODY = "Õâ Ã´ ¿ì ¾Í Àë ¿ª £¿",
        QUITYES = "ÎÒ Ëµ ÍË ³ö !",
        QUITNO = "Ëã ÁË ¡­¡­",
        OPTIONS = "Éè ÖÃ ",
        CONTROLS = "¿Ø ÖÆ ",
        SAVEANDQUIT = "±£ ´æ ²¢ ÍË ³ö ",
        QUIT = "ÍË ³ö ",
        CONTINUE = "¼Ì Ðø ",
    },

    MODSSCREEN = {
        APPLY = "È· ¶¨ ",
        CANCEL = "È¡ Ïû ",
        MOREMODS = "¸ü ¶à Mod ",
        VERSION = "°æ ±¾ %s",
        AUTHORBY = "ÓÉ %s ÖÆ ×÷ ",
        MODLINK = "´ø ÎÒ È¥ Mod Ò³ £¡ ",
        MODLINKGENERIC = "Mod ÌÖ ÂÛ Ò³ ",
        ENABLE = "Æô ÓÃ ",
        DISABLE = "½û ÓÃ ",
        WORKING_NORMALLY = "ÒÑ °² ×° ",
        WILL_ENABLE = "Mod ½« ±» Æô ÓÃ",
        WILL_DISABLE = "Mod ½« ±» ½û ÓÃ.",
        DISABLED_MANUAL = "ÒÑ ½û ÓÃ",
        DISABLED_ERROR = "ÉÏ ´Î Æô ¶¯ Ê± ±À À£ £¬ ×Ô ¶¯ ±» ½û ÓÃ ",
        DISABLED_OLD = "Mod ÊÇ Ö® Ç° µÄ £¬ ×Ô ¶¯ ±» ½û ÓÃ",
        STATUS = {
            WORKING_NORMALLY = "Æô ÓÃ ",
            WILL_ENABLE = "Òª Æô ÓÃ µÄ ",
            WILL_DISABLE = "Òª ½û ÓÃ µÄ ",
            DISABLED_MANUAL = "¹Ø ±Õ ",
            DISABLED_ERROR = "±À À£ ÁË £¡",
            DISABLED_OLD = "Ö® Ç° µÄ £¡",
        },
        NO_MODS = "Äã Ã» ÓÐ °² ×° ÈÎ ºÎ Mod£¬ µ« ÊÇ Äã ¿É ÒÔ ÔÚ Klei ÂÛ Ì³ ÉÏ ÏÂ ÔØ Ò» Ð© ",
        NO_MODS_LINK = "´ø ÎÒ È¥ Mod Ò³ £¡ ",
        WORKSHOP = {
            UPDATE_TITLE = "Steam Éç Çø",
            STATE_LIST = "¼ì ²é ¹¤ ×÷ ÊÒ µÄ ¶© ÔÄ¡­¡­",
            STATE_DETAILS = "Õý ÔÚ Ñé Ö¤ Mod Ï¸ ½Ú ¡­¡­",
            STATE_DOWNLOAD_0 = "Õý ÔÚ Ñé Ö¤ Mod »º ´æ ¡­¡­",
            STATE_DOWNLOAD = "ÏÂ ÔØ Mod £º",
            STATE_DOWNLOAD_PERCENT = "°Ù ·Ö Ö® %s ",
        },
        TOPMODS = "Mod ÅÅ ÐÐ ",
        FEATUREDMOD = "ÌØ É« Mod",
        LOADING = "¶Á È¡ ÖÐ ",
        RESTART_TITLE = "Ðè Òª ÖØ Æô ",
        RESTART_REQUIRED = "Äã Ðè Òª ÖØ ÐÂ Æô ¶¯ ÓÎ Ï· ÒÔ ¿ª Æô »ò ¹Ø ±Õ Mod",
        RESTART = "ÏÖ ÔÚ ÍË ³ö ",
    },
    
    CUSTOMIZATIONSCREEN =
    {
        APPLY = "Ó¦ ÓÃ ",
        CANCEL = "È¡ Ïû",
        PRESETTITLE = "Ô¤ Éè ",
        DEFAULT_PRESET_DESC = "ºÜ ¶à Öí ¡¢Ö© Öë ºÍ Ò» ¸ö ¸ß Äñ ³² ",
        LOSECHANGESTITLE = "·Å Æú ¸ü ¸Ä £¿",
        LOSECHANGESBODY = "Ê¹ ÓÃ ÐÂ µÄ Ä¬ ÈÏ Éè ÖÃ £¬ ·Å Æú ×Ô ¶¨ Òå ¸ü ¸Ä £¿",
        YES = "ÊÇ",
        NO = "·ñ",
        CUSTOMDESC = "Äã µÄ µØ ÅÌ £¬ Äã ×ö Ö÷ £¡",
        CUSTOM = "£¨ ×Ô ¶¨ Òå £©",
        BACKTITLE = "·Å Æú ¸ü ¸Ä",
        BACKBODY = "·Å Æú ¶Ô ÊÀ ½ç Éú ³É µÄ Ñ¡ Ïî ¸ü ¸Ä £¿",

        PRESETLEVELS = {
                "Ä¬ ÈÏ", 
                "¿ì ËÙ ¿ª Ê¼",              -- Bootstrap the start
                "ÓÀ Ò¹",   
                "³± Êª »· ¾³",              -- Too much water - swamp etc
                "¸É Ôï Ê¢ ÏÄ",              -- Less water, no swamp etc
                "¶¬ Ìì Äã ¸Ã Ôõ Ã´ °ì £¿",  -- Winter focus
                "µº ¡¢ Äã ¡¢ ¸« Í·",        -- Island hopping
                "·è ¿ñ µÄ ·è ¿ñ",           -- Focus on sanity play
                "Ò¹ ¼ä ±í ÑÝ ",             -- Focus on nighttime play
                },      
                
        PRESETLEVELDESC = {
            "±ê ×¼ ¡¶¼¢ »Ä ¡·Ìå Ñé ",
            "ÔÚ ¸ü ¼Ó ¼è ÏÕ µÄ ÊÀ ½ç ÖÐ ¸ü ¿ì µØ ¿ª Ê¼",
            "±ê ×¼ ¡¶¼¢ »Ä ¡·ºÚ °µ Å¤ Çú µÄ Ìå Ñé ",
            "±ê ×¼ ¡¶¼¢ »Ä ¡·Ìå Ñé 4",
            "±ê ×¼ ¡¶¼¢ »Ä ¡·Ìå Ñé 5",
            "±ê ×¼ ¡¶¼¢ »Ä ¡·Ìå Ñé 6",
            "±ê ×¼ ¡¶¼¢ »Ä ¡·Ìå Ñé 7",
            "±ê ×¼ ¡¶¼¢ »Ä ¡·Ìå Ñé 8",
            "±ê ×¼ ¡¶¼¢ »Ä ¡·Ìå Ñé 9",
            "±ê ×¼ ¡¶¼¢ »Ä ¡·Ìå Ñé 10",
        }
                
    },
    
    NEWGAMESCREEN =
    {
        TITLE = "ÐÂ ÓÎ Ï·",
        CANCEL = "È¡ Ïû ",
        CHANGECHARACTER = "½Ç É« Ñ¡ Ïî",
        CUSTOMIZE = "ÊÀ ½ç Ñ¡ Ïî",
        START = "¿ª Ê¼",
        DLCON = "Æô ÓÃ ¡¶ ¾Þ ÈË µÄ Í³ ÖÎ ¡· ×Ê ÁÏ Æ¬",
        DLCOFF = "Í£ ÓÃ ¡¶ ¾Þ ÈË µÄ Í³ ÖÎ ¡· ×Ê ÁÏ Æ¬",
    },

    SLOTDETAILSSCREEN =
    {
        TITLE = "Î» ÖÃ",
        CANCEL = "È¡ Ïû",
        CONTINUE = "¼Ì Ðø",
        PLAY = "¿ª Ê¼ ÓÎ Ï·",
        RESTART = "ÖØ ÐÂ ¿ª Ê¼",
        DELETE = "É¾ ³ý",
        CHANGECHARACTER = "¸Ä ±ä ½Ç É«",
    },

    LOADGAMESCREEN=
    {
        CANCEL = "È¡ Ïû",
        TITLE = "Ñ¡ Ôñ Î» ÖÃ",
        NEWGAME = "ÐÂ ÓÎ Ï·",
        ADVENTURE = "Ã° ÏÕ ",
        SURVIVAL = "Éú ´æ ",
        CAVE = "¶´ Ñ¨ ",
        RESTART = "ÖØ ÐÂ ¿ª Ê¼ ",        
        CAVE = "¶´ Ñ¨ Éî ¶È ",
        MODDED = "Ä£ Ê½",
    },

    MORGUESCREEN=
    {
        MORGUE = "ËÀ Íö ÈÕ Ö¾",
        TITLE = "¸¼ ¸æ ",
        OK = "È· ¶¨",
        DAYS_LIVED = "´æ »î Ê± ¼ä ",
        DECEASED = "ÒÑ ËÀ Íö",
        CAUSE = "ËÀ Íö Ô­ Òò",
        MODE = "Ä£ Ê½",
        LEVELTYPE = {
            "Éú ´æ",
            "¶´ Ñ¨ ",
            "Ã° ÏÕ ",
            "²â ÊÔ ",
            "Î´ Öª ",
         },    
    },

    CONTROLSSCREEN=
    {
        -- Must match the Control enum in DontStarveInputHandler.h
        -- Must match constants.lua CONTROLS_*
        CONTROLS = {
            "Ö÷ Òª ",
            "´Î Òª ",
            "¹¥ »÷ ",
            "¼ì ²é Îï Æ· ",
            "ÐÐ ¶¯ ",
            "Ïò ÉÏ ÒÆ ¶¯ ",
            "Ïò ÏÂ ÒÆ ¶¯ ",
            "Ïò ×ó ÒÆ ¶¯ ",
            "Ïò ÓÒ ÒÆ ¶¯ ",
            "·Å ´ó ",
            "Ëõ Ð¡ ",
            "Äæ Ê± Õë Ðý ×ª ",
            "Ë³ Ê± Õë Ðý ×ª",
            "ÔÝ Í£",
            "µØ Í¼ ",
            "Îï Æ· 1",
            "Îï Æ· 2",
            "Îï Æ· 3",
            "Îï Æ· 4",
            "Îï Æ· 5",
            "Îï Æ· 6",
            "Îï Æ· 7",
            "Îï Æ· 8",
            "Îï Æ· 9",
            "Îï Æ· 10",
            "²Ë µ¥ Ïò ÉÏ",
            "²Ë µ¥ Ïò ÏÂ",
            "²Ë µ¥ Ïò ×ó",
            "²Ë µ¥ Ïò ÓÒ",
            "½Ó ÊÜ ²Ë µ¥ ",
            "È¡ Ïû ²Ë µ¥ ",
            "ÉÏ Ò» Ò³ ²Ë µ¥",
            "ÏÂ Ò» Ò³ ²Ë µ¥",
            "ÉÏ Ò» ¸ö ²Ë µ¥ Öµ",
            "ÏÂ Ò» ¸ö ²Ë µ¥ Öµ",
            "ÄÃ ×ß Ò» °ë ",
            "½» »» ×° Ïä ",
            "»» ×° Ïä (Ò» °ë)",
            "Ç¿ ÖÆ ¼ì ²é (mod)",
            "Ç¿ ÖÆ ¹¥ »÷ (mod)",
            "Ç¿ ÖÆ ×° Ïä  (mod)",
            "Ç¿ ÖÆ ¶Ñ ·Å  (mod)",
            "µ÷ ÊÔ ¿Ø ÖÆ Ì¨ ",
            "µ÷ ÊÔ ÈÕ Ö¾ ",
            "µ÷ ÊÔ äÖ È¾ ",
            "´ò ¿ª Îï Æ· À¸ ",
            "´ò ¿ª ¹¤ ÒÕ À¸ ",
            "Îï Æ· À¸ Ïò ×ó ",
            "Îï Æ· À¸ Ïò ÓÒ ",
            "Îï Æ· À¸ Ïò ÉÏ ",
            "Îï Æ· À¸ Ïò ÏÂ ",
            "¼ì ²é Îï Æ·",
            "Ê¹ ÓÃ ×Ô Éí Îï Æ·",
            "Ê¹ ÓÃ ÖÜ Î§ Îï Æ·",
            "¶ª µô Îï Æ· ",
            "Îï Æ· ¶Ñ µþ µ÷ Õû ",
            "¹¥ »÷ ", --controller version
            "¶¯ ×÷", --controller version
            "¶¯ ×÷ £¨°´ ×¡ Alt£©",
            "Ê¹ ÓÃ Ñ¡ ÖÐ Ïî Îï Æ· ",
            "·Å ´ó µØ Í¼ ",
            "Ëõ Ð¡ µØ Í¼ ",
            "µ÷ ÊÔ ²Ë µ¥",
        },

        DEVICE_TITLE = "¿Ø ÖÆ",
        APPLY = "½Ó ÊÜ",
        RESET = "ÖØ ÖÃ", 
        CANCEL = "È¡ Ïû",  
        CLOSE = "¹Ø ±Õ",    
        YES = "ÊÇ",        
        NO = "·ñ",      
        CONTROL_SELECT = " ¡ª¡ª Ñ¡ Ôñ ÐÂ µÄ Êä Èë ¡ª¡ª",
        DEFAULT_CONTROL_TEXT = "Ä¬ ÈÏ £º %s",
        LOSE_CHANGES_TITLE = "·Å Æú ¸ü ¸Ä £¿ ",
        LOSE_CHANGES_BODY = "Äã Òª ·Å Æú Ëù ÓÐ µÄ ¸Ä ±ä Âð £¿",
        -- INPUT_NAMES corresponds to DeviceType enum in InputDefinitions.h
        INPUT_NAMES = {
            [1] = "¼ü ÅÌ ºÍ Êó ±ê ",
            [2] = "Xbox360 ¿Ø ÖÆ Æ÷ ",
            [3] = "PS4 ¿Ø ÖÆ Æ÷ ",
            [4] = "Vita Ò£ ¿Ø ÓÎ Ï·",
            [5] = "Í¨ ÓÃ ¿Ø ÖÆ Æ÷ ",
            [6] = "´¥ Ãþ Êä Èë",
            [7] = "Î´ Öª",
            },

        INPUTS = { 
            -- KeyBoardMouse
            [1] = {                   
                -- Keyboard buttons       
                [0] = "Unknown",         
                [8] = "Backspace",
                [9] = "Tab", -- KEY_TAB         
                [12] = "Clear", -- KEY_CLEAR        
                [13] = "Enter", -- KEY_RETURN       
                [19] = "Pause", -- KEY_PAUSE        
                [27] = "Esc", -- KEY_ESCAPE     
                [32] = "Space", -- KEY_SPACE        
                --[33] = "!", -- KEY_EXCLAIM        
                --[34] = "", -- KEY_QUOTEDBL    
                --[35] = "", -- KEY_HASH        
                --[36] = "", -- KEY_DOLLAR      
                --[38] = "", -- KEY_AMPERSAND   
                [39] = "'", -- KEY_QUOTE        
                --[40] = "", -- KEY_LEFTPAREN   
                --[41] = "", -- KEY_RIGHTPAREN  
                --[42] = "", -- KEY_ASTERISK    
                --[43] = "", -- KEY_PLUS        
                [44] = ",", -- KEY_COMMA        
                [45] = "-", -- KEY_MINUS        
                [46] = ".", -- KEY_PERIOD       
                [47] = "/", -- KEY_SLASH        
                [48] = "0", -- KEY_0            
                [49] = "1", -- KEY_1            
                [50] = "2", -- KEY_2            
                [51] = "3", -- KEY_3            
                [52] = "4", -- KEY_4            
                [53] = "5", -- KEY_5            
                [54] = "6", -- KEY_6            
                [55] = "7", -- KEY_7            
                [56] = "8", -- KEY_8            
                [57] = "9", -- KEY_9            
                --[58] = "", -- KEY_COLON       
                [59] = "Semicolon", -- KEY_SEMICOLON        ;
                [60] = "<", -- KEY_LESS     
                [61] = "Equals", -- KEY_EQUALS              =
                [62] = ">", -- KEY_GREATER      
                --[63] = "", -- KEY_QUESTION    
                --[64] = "", -- KEY_AT      
                    
                [91] = "Left Bracket", -- KEY_LEFTBRACKET   [
                [92] = "Backslash", -- KEY_BACKSLASH        \\
                [93] = "Right Bracket", -- KEY_RIGHTBRACKET [
                --[94] = "", -- KEY_CARET       
                --[95] = "", -- KEY_UNDERSCORE  
                [96] = "`", -- KEY_BACKQUOTE    
                [97] = "A", -- KEY_A            
                [98] = "B", -- KEY_B            
                [99] = "C", -- KEY_C            
                [100] = "D", -- KEY_D           
                [101] = "E", -- KEY_E           
                [102] = "F", -- KEY_F           
                [103] = "G", -- KEY_G           
                [104] = "H", -- KEY_H           
                [105] = "I", -- KEY_I           
                [106] = "J", -- KEY_J           
                [107] = "K", -- KEY_K           
                [108] = "L", -- KEY_L           
                [109] = "M", -- KEY_M           
                [110] = "N", -- KEY_N           
                [111] = "O", -- KEY_O           
                [112] = "P", -- KEY_P           
                [113] = "Q", -- KEY_Q           
                [114] = "R", -- KEY_R           
                [115] = "S", -- KEY_S           
                [116] = "T", -- KEY_T           
                [117] = "U", -- KEY_U           
                [118] = "V", -- KEY_V           
                [119] = "W", -- KEY_W           
                [120] = "X", -- KEY_X           
                [121] = "Y", -- KEY_Y           
                [122] = "Z", -- KEY_Z           
                [127] = "Delete", -- KEY_DELETE     

                [256] = "Num 0", -- KEY_KP0             
                [257] = "Num 1", -- KEY_KP1             
                [258] = "Num 2", -- KEY_KP2             
                [259] = "Num 3", -- KEY_KP3             
                [260] = "Num 4", -- KEY_KP4             
                [261] = "Num 5", -- KEY_KP5             
                [262] = "Num 6", -- KEY_KP6             
                [263] = "Num 7", -- KEY_KP7             
                [264] = "Num 8", -- KEY_KP8             
                [265] = "Num 9", -- KEY_KP9             
                [266] = "Num .", -- KEY_KP_PERIOD       
                [267] = "Num /", -- KEY_KP_DIVIDE       
                [268] = "Num *", -- KEY_KP_MULTIPLY     
                [269] = "Num -", -- KEY_KP_MINUS        
                [270] = "Num +", -- KEY_KP_PLUS         
                [271] = "Num Enter", -- KEY_KP_ENTER        
                --[272] = "", -- KEY_KP_EQUALS      

                [273] = "Up", -- KEY_UP         
                [274] = "Down", -- KEY_DOWN     
                [275] = "Right", -- KEY_RIGHT       
                [276] = "Left", -- KEY_LEFT     
                [277] = "Insert", -- KEY_INSERT     
                [278] = "Home", -- KEY_HOME     
                [279] = "End", -- KEY_END           
                [280] = "Page Up", -- KEY_PAGEUP        
                [281] = "Page Down", -- KEY_PAGEDOWN    
                           
                [282] = "F1", -- KEY_F1         
                [283] = "F2", -- KEY_F2         
                [284] = "F3", -- KEY_F3         
                [285] = "F4", -- KEY_F4         
                [286] = "F5", -- KEY_F5         
                [287] = "F6", -- KEY_F6         
                [288] = "F7", -- KEY_F7         
                [289] = "F8", -- KEY_F8         
                [290] = "F9", -- KEY_F9         
                [291] = "F10", -- KEY_F10           
                [292] = "F11", -- KEY_F11           
                [293] = "F12", -- KEY_F12           
                [294] = "F13", -- KEY_F13           
                [295] = "F14", -- KEY_F14           
                [296] = "F15", -- KEY_F15           
                           
                [300] = "Num Lock", -- KEY_NUMLOCK      
                [301] = "Caps Lock", -- KEY_CAPSLOCK    
                [302] = "Scroll Lock", -- KEY_SCROLLOCK 
                [303] = "Right Shift", -- KEY_RSHIFT        
                [304] = "Left Shift", -- KEY_LSHIFT     
                [305] = "Right Control", -- KEY_RCTRL       
                [306] = "Left Control", -- KEY_LCTRL        
                [307] = "Right Alt", -- KEY_RALT        
                [308] = "Left Alt", -- KEY_LALT     
                [309] = "Right Meta", -- KEY_RMETA      
                [310] = "Left Meta", -- KEY_LMETA       
                [311] = "Left Windows", -- KEY_LSUPER       /**< Left "Windows" key */
                [312] = "Right Windows", -- KEY_RSUPER      /**< Right "Windows" key */
                [313] = "Mode", -- KEY_MODE         /**< "Alt Gr" key */
                [314] = "Compose", -- KEY_COMPOSE       /**< Multi-key compose key */

                [315] = "Help", -- KEY_HELP     
                [316] = "Print Screen", -- KEY_PRINT        
                --[317] = "", -- KEY_SYSREQ     
                --[318] = "", -- KEY_BREAK      
                [319] = "Menu", -- KEY_MENU     
                [320] = "Power", -- KEY_POWER       /**< Power Macintosh power key */
                [321] = "Euro", -- KEY_EURO         /**< Some european keyboards */
                [322] = "Undo", -- KEY_UNDO         /**< Atari keyboard has Undo */
                
                [400] = "Alt", -- KEY_ALT
                [401] = "Control", -- KEY_CTRL
                [402] = "Shift", -- KEY_SHIFT
                
                -- Mouse controls
                [1000] = "Left Mouse Button",
                [1001] = "Right Mouse Button",
                [1002] = "Middle Mouse Button",
                [1003] = "Mouse Scroll Up",
                [1004] = "Mouse Scroll Down", 
            },
            -- Xbox360
            [2] = { 
                -- Digital
                "\142",--"DPad Up"
                "\139",--"DPad Down"
                "\140",--"DPad Left",
                "\141",--"DPad Right"
                "\131",--"Start",
                "\132",--"Back",
                "\133",--"Left Stick"
                "\136",--"Right Stick"
                "\134",--"Left Bumper",
                "\137",--"Right Bumper"
                "\127",--Button A",
                "\128",--"Button B",
                "\129",--"Button X",
                "\130",--"Button Y",    
                  
                -- Analog          
                "\145",--"Left Thumb Left",
                "\146",--"Left Thumb Right",
                "\144",--"Left Thumb Down",
                "\143",--"Left Thumb Up",
                "\149",--"Right Thumb Left",
                "\150",--"Right Thumb Right",
                "\148",--"Right Thumb Down",
                "\147",--"Right Thumb Up",
                "\135",--"Left Trigger",
                "\135",--"Left Trigger",
                "\138",--"Right Trigger",
                "\138",--"Right Trigger",
            }, 
            -- Generic
            [3] = { 
                -- Digital
                "(Button %d)",
                
                -- Directional
                "(DPad %d Up)",
                "(DPad %d Down)",
                "(DPad %d Left)",
                "(DPad %d Right)",
                
                -- Analog
                "(-X Axis)",
                "(+X Axis)",
                "(-Y Axis)",
                "(+Y Axis)",
                "(-Z Axis)",
                "(+Z Axis)",
                "(-X Rotation)",
                "(+X Rotation)",
                "(-Y Rotation)",
                "(+Y Rotation)",
                "(-Z Rotation)",
                "(+Z Rotation)",
                "(Slider 0)",
                "(Slider 0)",
                "(Slider 1)",
                "(Slider 1)",
            },
            -- PS4
            [4] = { 
                -- Digital
                "\224\162\188",--"DPad Up"	--238
                "\224\162\191",--"DPad Down"	-- 241
                "\224\162\190",--"DPad Left",  --240
                "\224\162\189",--"DPad Right" --239         	
                "\224\163\199",--"Start",	--249
                "\224\163\198",--"Back",	--248
                "\224\163\197",--"Left Stick" --247
                "\224\163\194",--"Right Stick" --244
                "\224\163\196",--"Left Bumper", --246
                "\224\163\193",--"Right Bumper" --243
                "\224\163\203",--Button A", --253
                "\224\163\202",--"Button B", --252
                "\224\163\201",--"Button X", --251
                "\224\163\200",--"Button Y",    --250
                  
                -- Analog          
                "\224\162\185",--"Left Thumb Left", --235
                "\224\162\184",--"Left Thumb Right", --234
                "\224\162\186",--"Left Thumb Down", --236
                "\224\162\187",--"Left Thumb Up", --237
                "\224\162\181",--"Right Thumb Left", --231
                "\224\162\180",--"Right Thumb Right",--230
                "\224\162\182",--"Right Thumb Down",--232
                "\224\162\183",--"Right Thumb Up", --233
                "\224\163\195",--"Left Trigger",   --245
                "\224\163\195",--"Left Trigger",
                "\224\163\192",--"Right Trigger",   --242
                "\224\163\192",--"Right Trigger",   --242
            },
            -- Vita Remote Play
            [5] = { 
                -- Digital
                "\224\162\188",--"DPad Up"
                "\224\162\191",--"DPad Down"
                "\224\162\190",--"DPad Left",
                "\224\162\189",--"DPad Right"
                "\224\163\199",--"Start",
                "\224\163\198",--"Back",
                "\224\163\197",--"Left Stick"
                "\224\163\194",--"Right Stick"
                "\224\162\179",--"L",
                "\224\162\178",--"R"
                "\224\163\203",--Button A",
                "\224\163\202",--"Button B",
                "\224\163\201",--"Button X",
                "\224\163\200",--"Button Y",    
                  
                -- Analog          
                "\224\162\185",--"Left Thumb Left",
                "\224\162\184",--"Left Thumb Right",
                "\224\162\186",--"Left Thumb Down",
                "\224\162\187",--"Left Thumb Up",
                "\224\162\181",--"Right Thumb Left",
                "\224\162\180",--"Right Thumb Right",
                "\224\162\182",--"Right Thumb Down",
                "\224\162\183",--"Right Thumb Up",
                "\224\162\177",--"Left Trigger",
                "\224\162\177",--"Left Trigger",
                "\224\162\176",--"Right Trigger",
                "\224\162\176",--"Right Trigger",
            },
            --Unknown
            [6] = {
                "Unknown",
                " -- None selected -- ",
            },
        },
        PS4 = {
            TOUCHPAD = "µØ Í¼",
            OPTIONS = "ÔÝ Í£",

            L1 = "Äæ Ê± Õë Ðý ×ª",
            R1 = "Ë³ Ê± Õë Ðý ×ª",

            L2 = "´ò ¿ª ¹¤ ÒÕ À¸",
            R2 = "´ò ¿ª Îï Æ· À¸",

            DPAD_UP = "¼ì ²é Ëü",
            DPAD_LEFT = "¶Ô ÊÀ ½ç Ê¹ ÓÃ",
            DPAD_BOTTOM = "¶ª µô Ëü",
            DPAD_RIGHT = "¶Ô ×Ô ¼º Ê¹ ÓÃ",

            L3 = "×ß ¶¯",

            TRIANGLE = "¼ì ²é",
            CIRCLE = "¶¯ ×÷ £¨ °´ ×¡ ALT £© / È¡ Ïû",
            CROSS = "ÐÐ ¶¯ / ½Ó ÊÜ",
            SQUARE = "¹¥ »÷",

            R3 = "´Ó ¿â ´æ ÖÐ Ñ¡ Ôñ",
        },
    },

    UNLOCKMAXWELL=
    {
        TITLE = "Í¬ Çé £¿ ",
        BODY1 = "Õâ Ô¿ ³× ¿´ Æð À´ ºÜ ºÏ ÊÊ ¡£Äã ×Ô ÓÉ ÁË ",
        BODY2 ="£¬ µ« ÎÒ »³ ÒÉ %s ²¶ »ñ Õß ½« »á ºÜ ¸ß ÐË ¡­¡­",
        YES = "ÊÇ",
        NO = "·ñ",
    },

    RESETCAVE=
    {
        TITLE="ÖØ ÖÃ Õâ ¸ö ¶´ Ñ¨ £¿",
        BODY="Äã È· ¶¨ Òª ÔÚ Õâ ÍÚ Ò» ¸ö ÐÂ ¶´ Ñ¨ Âð £¿",
        YES="ÊÇ",
        NO="·ñ",
    },
    
    STARTADVENTURE=
    {
        TITLE="Ã° ÏÕ µÄ ´ó ÃÅ £¡ ",
        BODY="Èç ¹û ÔÚ Ã° ÏÕ Ä£ Ê½ ÖÐ ËÀ Íö £¬ Äã »á »Ø µ½ Õâ ¸ö ´« ËÍ ÃÅ ÖØ ÐÂ ¿ª Ê¼ Ã° ÏÕ ¡£\n\nÄã Òª Ì¤ ÉÏ Ò» ¸ö Ñ° ÕÒ Âó Ë¹ Íþ ¶û µÄ Âþ ³¤ ¼è ÄÑ µÄ ÂÃ ³Ì ¡£Äã Òª ÔÚ 5¸ö ÊÀ ½ç Àï ´æ »î £¬ Ã¿ Ò» ¸ö ¶¼ Ëæ »ú ²ú Éú ÐÂ µÄ Ìô Õ½ ",
        BODY_TEST="Èç ¹û ÔÚ Ã° ÏÕ Ä£ Ê½ ÖÐ ËÀ Íö £¬ Äã »á »Ø µ½ Õâ ¸ö ´« ËÍ ÃÅ ÖØ ÐÂ ¿ª Ê¼ Ã° ÏÕ ¡£\n\nÄã Òª Ì¤ ÉÏ Ò» ¸ö Ñ° ÕÒ Âó Ë¹ Íþ ¶û µÄ Âþ ³¤ ¼è ÄÑ µÄ ÂÃ ³Ì ¡£Äã Òª ÔÚ 5¸ö ÊÀ ½ç Àï ´æ »î £¬ Ã¿ Ò» ¸ö ¶¼ Ëæ »ú ²ú Éú ÐÂ µÄ Ìô Õ½ ",
        YES="ÎÒ ÃÇ ×ß £¡",
        NO="±ð ÂÒ ÅÜ",
    },

    ENDGAME=
    {
        TITLE="¾ç ÖÕ ",
        BODY1 = "ÂÖ »Ø ÓÖ ½« ¿ª Ê¼ ¡£»á  ",
        BODY2 = " ÓÐ ³ö Â· Âð £¿ \nÒ² Ðí %sÒ² »á ¶Ô Õâ ¸ö µØ ·½ ¸Ð µ½ Ñá ¾ë £¬ Ê¹ ÓÃ %sÁ¦ Á¿ ³¢ ÊÔ Î´ Öª ¡£\n\nÕÆ ¿Ø ´Ë µØ µÄ Éñ ÃØ Éú Îï ÈÔ È» Ç± ·ü ÔÚ °µ ´¦ £¬ ÐÂ µÄ Ìô Õ½ ¼´ ½« ½Ò Ïþ ¡£\n\nÖ± µ½ ÄÇ Ê± £¬ \n-¡¶¼¢ »Ä ¡·ÍÅ ¶Ó -",
        YES= "Îª ÁË ¿Æ Ñ§ £¡",
    },

    GENDERSTRINGS =
    {
        MALE = 
        {
            ONE = "Ëû ",
            TWO = "Ëû µÄ",
        },
        FEMALE = 
        {
            ONE = "Ëý",
            TWO = "Ëý µÄ",
        },
        ROBOT =
        {
            ONE = "Ëü",
            TWO = "Ëü µÄ",
        },
    },

    SANDBOXMENU =
    {
        TITLE = "ÊÀ ½ç ¶¨ ÖÆ",
        TITLEDETAIL = "",
        
        EASY = "²» ¼ò µ¥",
        MEDIUM = "Ïà µ± À§ ÄÑ",
        HARD = "¼« Îª ¼è ÄÑ ",

        GENERATE = "È· ¶¨",
        MAINMENU = "È¡ Ïû",
        
        CHOICEMONSTERS = "¹Ö Îï ",
        CHOICEANIMALS = "¶¯ Îï ",
        CHOICERESOURCES = "×Ê Ô´ ",
        CHOICEFOOD =    "Ê³ Îï",
        CHOICECOOKED = "Ô¤ ÖÃ Ê³ Îï ",     
        CHOICEAMTDAY = "ÓÎ Ï· Ê± ¼ä", 
        CHOICEMISC = "ÊÀ ½ç",   
                
        DAY = "°× Ìì",
        NIGHT = "»Æ »è",
        DUSK = "ºÚ Ò¹",
        
        SLIDESHORT = "¶Ì ",
        SLIDELONG = "³¤ ",
        SLIDEALL = "½ö ÓÐ ",
        
        SLIDEDEFAULT = "Ä¬ ÈÏ ",
        
        SLIDENEVER = "ÎÞ",
        SLIDERARE = "½Ï ÉÙ ",
        SLIDEOFTEN = "½Ï ¶à ",
        SLIDEALWAYS = "´ó Á¿ ",
        
        SLIDEVERYSLOW = "¼« Âý",
        SLIDESLOW = "Âý",
        SLIDEFAST = "¿ì",
        SLIDEVERYFAST = "¼« ¿ì",
        
        DEFAULT = "Çï Ìì »ò ´º Ìì",
        SUMMER = "ÏÄ Ìì",
        WINTER = "¶¬ Ìì",
        SPRING = "´º Ìì",
        AUTUMN = "Çï Ìì",
        BOTH = "Á½ ¸ö ",
        ALLSEASONS = "È« ¼¾ ½Ú",
        CLASSIC = "Çï Ìì £¬ ¶¬ Ìì",
        DLC = "´º Ìì £¬ ÏÄ Ìì",
        EXTREMETEMPS = "ÏÄ Ìì £¬ ¶¬ Ìì",
        STATICTEMPS = "Çï Ìì £¬ ´º Ìì",
        EXCLUDE = "Ã» ÓÐ",
        
        SLIDESMALL = "Ä¬ ÈÏ",
        SLIDESMEDIUM = "ÖÐ ÐÍ ",
        SLIDESLARGE = "´ó ÐÍ ",
        SLIDESHUGE = "¾Þ ÐÍ ",
        
        SLIDEVERYSIMPLE = "·Ç ³£ ¼ò µ¥ ",
        SLIDESIMPLE = "¼ò µ¥",
        SLIDECOMPLEX = "¸´ ÔÓ ",
        SLIDEVERYCOMPLEX = "·Ç ³£ ¸´ ÔÓ ",

        BRANCHINGMOST = "×î ¶à ",
        BRANCHINGANY = "Ä¬ ÈÏ",
        BRANCHINGLEAST = "×î ÉÙ",
        BRANCHINGNEVER = "´Ó ²» ",

        LOOPNEVER = "´Ó ²» ",
        LOOPRANDOM = "Ä¬ ÈÏ",
        LOOPALWAYS = "Ê¼ ÖÕ ",
        
        USEPRESET = "Ô¤ Éè",
        CHAPTERS = {
                "µÚ 1ÕÂ / 5 ÕÂ ",
                "µÚ 2ÕÂ / 5 ÕÂ",
                "µÚ 3ÕÂ / 5 ÕÂ",
                "µÚ 4ÕÂ / 5 ÕÂ ",
                "µÚ 5ÕÂ / 5 ÕÂ ",
                "Î² Éù",
        },
        ADVENTURELEVELS = {
                "Àä µ­ µÄ ½Ó ´ý ", 
                "¶¬ ¼¾ Ö® Íõ", 
                "ÓÎ Ï· ½ø ÐÐ ÖÐ", 
                "Èº µº",
                "Á½ ¸ö ÊÀ ½ç", 
                "ºÚ °µ", 

                "´ì °Ü ",
                },
        NONE = "ÎÞ ",
        NONEAVAILABLE = "ÎÞ ¿É ÓÃ ",
        MODIFYTASKS = "ÐÞ ¸Ä ÈÎ Îñ ",
        
        YES ="ÊÇ",
        NO = "·ñ",
    },
    
    SAVELOAD = 
   {        
        SAVE_FAILED = "ÔÚ ±£ ´æ Ê± ·¢ Éú ´í Îó",
        LOAD_FAILED = "ÔÚ ¶Á È¡ Ê± ·¢ Éú ´í Îó",
        DELETE_FAILED = "ÔÚ É¾ ³ý Ê± ·¢ Éú ´í Îó",	    
        DATA_DAMAGED = "Äã µÄ ´æ µµ ÒÑ Ëð »µ ²¢ ÇÒ ÎÞ ·¨ Ê¹ ÓÃ",
        DISABLE_AUTOSAVE = "Äã È· ¶¨ Òª ½û ÓÃ \n ×Ô ¶¯ ±£ ´æ ¹¦ ÄÜ £¿",
        
        OVERWRITE = "¸² ¸Ç",	    
        RETRY = "ÖØ ÊÔ",
        CANCEL = "È¡ Ïû",
        YES = "ÊÇ",
        NO = "·ñ",
    },
    
    QUITTINGTITLE = "·Å Æú £¡",
    QUITTING = "ÒÀ ¿¿ ¿Æ Ñ§ ¼¼ Êõ ",
    
    TELEPORTTITLE = "¼Ì Ðø ÂÃ ³Ì £¿",
    TELEPORTBODY_SURVIVAL = "Õâ »á ´Ý »Ù Äã µ± Ç° µÄ ÊÀ ½ç £¬ µ« Äã µÄ Îï Æ· ½« »á ±£ Áô ",
    TELEPORTBODY_ADVENTURE = "Õâ »á ÒÆ ³ý Äã Ëù ÓÐ µÄ Îï Æ· ²¢ ´Ý »Ù Äã µ± Ç° µÄ ÊÀ ½ç ¡£Ö» ÓÐ ÒÑ ±£ ´æ µÄ Îï Æ· ²Å ¿É ±£ Áô ÖÁ ÏÂ Ò» ¸ö ÊÀ ½ç",
    TELEPORTYES = "¿ª Ê¼ £¡",
    TELEPORTNO = "±ð ÂÒ ÅÜ",
}

--these are broken out into their own files for ease of editing
STRINGS.CHARACTERS =
{
    GENERIC = require "speech_wilson",
    WAXWELL = require "speech_maxwell",
    WOLFGANG = require "speech_wolfgang",
    WX78 = require "speech_wx78",
    WILLOW = require "speech_willow",
    WENDY = require "speech_wendy",
    WOODIE = require "speech_woodie",
    WICKERBOTTOM = require "speech_wickerbottom",
}--·­ÒëÏà¹Ø

STRINGS.LUCY =
{
    equipped=
    {
        "ÈÃ ÎÒ ÃÇ ÔÙ ¶à ¾â Ò» Ð© Ê÷ °É £¡",
        "½ñ Ìì ÊÇ É¢ ²½ µÄ ºÃ ÈÕ ×Ó £¡",
        "ÎÒ ÃÇ ¿É ÒÔ ×é ³É Ò» Ö§ ºÜ ºÃ µÄ ¶Ó Îé £¡",
        "Õâ ¸½ ½ü ¿Ï ¶¨ ÔÚ ÄÄ Àï ÓÐ Ê÷ ",
        "Îé µÏ £¡ ÔÙ ¶à ¾â Ò» Ð© Ê÷ £¡",
        "·± ÖØ µÄ ¹¤ ×÷ ºÍ ØÑ ·¦ Óé ÀÖ ÈÃ ÎÒ ¸ü Ïë ¾â Ê÷ ÁË",
        "¾â ¾â ¾â ¡£¹þ ",
    },

    on_ground =
    {
        "»Ø À´ £¡ ´ø ÉÏ ÎÒ ÃÇ °É £¡",
        "Äã È¥ ÄÄ Àï ÁË £¿",
        "´ø ÉÏ ÎÒ °É £¡",
        "Èç ¹û ÎÒ ±» Íµ ÁË Ôõ Ã´ °ì £¿ £¡",
    },

    in_container =
    {
        "Õâ Àï Õæ ºÚ £¡",
        "ÎÒ ºÜ º¦ ÅÂ £¡",
        "ÎÒ Ê² Ã´ ¶¼ ¿´ ²» µ½ ÁË £¡",
        "ÎÒ ÌÖ Ñá ´ý ÔÚ Õâ Àï £¡",
    },

    other_owner =
    {
        "Äã ²» ÊÇ Îé µÏ £¡",
        "·Å ÎÒ ÏÂ À´ £¡",
    },

    on_pickedup=
    {
        "Äã »Ø À´ À² £¡",
        "ÎÒ ºÜ Ïë Äã £¡",
        "Äã Ïë ¹ý ÎÒ £¿",
    },

    on_dropped=
    {
        "Äã »á »Ø À´ µÄ £¬ ¶Ô Âð £¿",
        "ÎÒ Ëµ Ê² Ã´ À´ ×Å £¿",
        "ÎÒ ¡­¡­²» Ã÷ °× £¡",
        "ÎÒ ÃÇ ÄÜ Ì¸ Ì¸ Âð £¿",
        "²» Òª Íü ÁË ÎÒ £¡",
    },

    on_chopped=
    {
        "ÍÛ Å¶ £¡",
        "Ò® £¡",
        "¿É ¶ñ µÄ Ê÷ £¡",
        "ßö ßö ßö £¡",
        "ÎÒ ÃÇ ³É ¹¦ ÁË £¡",
        "Ì« °ô ÁË £¡",
        "ÈÃ Ëù ÓÐ µÄ Ê÷ ¶¼ È¥ ËÀ °É £¡ ",
        "ÓÖ À´ ÁË £¡ ÈÃ ÎÒ ÃÇ ÔÙ ¾â Ò» ¸ö £¡",
        "×ª µÄ Æ¯ ÁÁ £¡",
        "Ì« ¼ò µ¥ ÁË £¡",
    },
    beaver_up_early=
    {
        "Äã »¹ ºÃ Âð £¿",
        "Äã ¿´ Æð À´ ÓÐ µã ÐÄ ²» ÔÚ ÑÉ £¬ Îé µÏ ",
        "Õâ Ö» ÊÇ Ò» ¿Ã Ê÷ °Õ ÁË £¡ Àä ¾² ",
    },
    beaver_up_mid=
    {
        "Îé µÏ £¿ Ìý µÃ µ½ Âð £¿",
        "Äã »ò Ðí Ó¦ ¸Ã Âý Ò» µã",
        "Ð¡ ÐÄ £¬ Äã »á ÈÃ ×Ô ¼º ²» Ë¬ µÄ £¡",
        "²» Òª ¾â µÄ Ì« ¿ì ¡£Äã Öª µÀ ÄÇ Ñù »á ·¢ Éú Ê² Ã´ £¡",
    },
    beaver_up_late=
    {
        "Îé µÏ £¡ Ð¡ ÐÄ £¡",
        "¿ª Ê¼ ÁË £¡",
        "Äã ¿´ Æð À´ ²» Ì« ºÃ £¡",
        "Äã Õý ÔÚ ³¤ ÑÀ £¡",
        "Ð¡ ÐÄ £¡ Äã Òª µ¹ ÁË £¡",
    },
    beaver_down_washigh=
    {
        "Õâ ¸ö Ì« ½ü ÁË £¬ Õæ Î£ ÏÕ £¡",
        "ÎÒ Ïë ÎÒ ÃÇ ²» »á ÓÐ ÊÂ µÄ.",
        "Äã ÏÖ ÔÚ ¿´ Æð À´ ºÃ ¶à ÁË",
        "ÏÖ ÔÚ ÔÝ Ê± ¹ý È¥ ÁË",
        "Ëü »Ø µ½ Ð¡ ÎÝ ÖÐ È¥ ÁË ¡£ºô £¡",
    },

    transform_beaver=
    {
        "Å¶ £¬ ²» £¡",
        "ÓÖ À´ ÁË ",
        "×ç Öä £¡",
        "ÎÒ ¾¯ ¸æ ¹ý Äã ÁË £¡",
        "Îé µÏ £¡",
    },
    transform_woodie=
    {
        "Äã »Ø À´ ÁË £¡",
        "¿ì µã £¡ ´ø ÉÏ ÎÒ £¡",
        "Äã »¹ ºÃ Âð £¿",
        "²» Òª ÔÙ ÈÃ ÄÇ Ñù µÄ ÊÂ Çé ·¢ Éú ÁË £¡",
        "Ò» Ð© ¶¼ »á ºÃ µÄ ¡£¼¯ ÖÐ ¾« Éñ £¡",
    }

}